import type { Lang } from '../settings.js';

/** The words of the leaderboards, in English and Indonesian. */
export const LEADERS_TEXT = {
  en: {
    title: 'LEADERBOARD',
    myClass: 'MY CLASS',
    global: 'GLOBAL',
    strike: 'HIGH STRIKE',
    days: 'MOST DAYS',
    city: 'CITY BUILDER',
    month: 'THIS MONTH',
    all: 'ALL TIME',
    close: 'CLOSE',
    loading: 'Loading...',
    points: (n: number) => `${n} pts`,
    dayCount: (n: number) => (n === 1 ? '1 day' : `${n} days`),
    folds: (n: number) => `${n} Folds`,
    grade: (g: number) => `Grade ${g}`,
    you: 'YOU',
    about: {
      strike: 'The best score in one race: class races, rooms and FIND A RIVAL. Points count effort against what was expected, so anyone can top it.',
      days: 'The days you played: practice, races, the smartboard. One a day at most, so coming back counts, not playing long.',
      city: 'The Folds in the finished buildings of your Fold Town. Build in MY FOLD TOWN with the Folds you earn.',
    },
    month1: 'A new month starts on the 1st (07:00 in Western Indonesia).',
    empty: {
      strike: 'No races yet. Win points in a class race or FIND A RIVAL to get on the board.',
      days: 'Nobody has played yet.',
      city: 'No finished buildings yet. A building counts once its building time is over.',
    },
    signIn: "Sign in to your class seat first (I'M IN A CLASS) to see your class.",
    offClass: 'Your teacher has taken your class off GLOBAL, so you do not show there.',
    offline: 'The leaderboards need the internet. Your plays are kept and count once you are back online.',
    failed: 'The leaderboard could not be loaded. Try again.',
    retry: 'TRY AGAIN',
  },
  id: {
    title: 'PAPAN PERINGKAT',
    myClass: 'KELASKU',
    global: 'GLOBAL',
    strike: 'HIGH STRIKE',
    days: 'PALING RAJIN',
    city: 'CITY BUILDER',
    month: 'BULAN INI',
    all: 'SEPANJANG MASA',
    close: 'TUTUP',
    loading: 'Memuat...',
    points: (n: number) => `${n} poin`,
    dayCount: (n: number) => `${n} hari`,
    folds: (n: number) => `${n} Folds`,
    grade: (g: number) => `Kelas ${g}`,
    you: 'KAMU',
    about: {
      strike: 'Skor terbaik dalam satu lomba: lomba kelas, ruang, dan CARI LAWAN. Poin menghitung usaha dibanding harapan, jadi siapa pun bisa juara.',
      days: 'Hari kamu bermain: latihan, lomba, smartboard. Paling banyak satu per hari, jadi yang dihitung rajin kembali, bukan lama bermain.',
      city: 'Folds di bangunan yang sudah selesai di Kota Lipatmu. Bangun di MY FOLD TOWN dengan Folds yang kamu dapat.',
    },
    month1: 'Bulan baru mulai tanggal 1 (pukul 07.00 WIB).',
    empty: {
      strike: 'Belum ada lomba. Kumpulkan poin di lomba kelas atau CARI LAWAN untuk masuk papan.',
      days: 'Belum ada yang bermain.',
      city: 'Belum ada bangunan yang selesai. Bangunan dihitung setelah waktu bangunnya habis.',
    },
    signIn: 'Masuk dulu ke kursi kelasmu (AKU DI KELAS) untuk melihat kelasmu.',
    offClass: 'Gurumu mengeluarkan kelasmu dari GLOBAL, jadi kamu tidak tampil di sana.',
    offline: 'Papan peringkat butuh internet. Permainanmu tersimpan dan dihitung saat kembali online.',
    failed: 'Papan peringkat belum bisa dimuat. Coba lagi.',
    retry: 'COBA LAGI',
  },
} satisfies Record<Lang, unknown>;

export type LeadersText = (typeof LEADERS_TEXT)['en'];
