import type { Access } from '../settings.js';
/**
 * Text of the home page in English (default) and Indonesian. Headings and
 * card titles are capitals, drawn with the paper letters.
 */
export type Lang = 'en' | 'id';

const EN = {
  playOn: 'PLAY ON',
  device: { computer: 'THIS COMPUTER', xr: 'META QUEST (XR)', smartboard: 'SMARTBOARD' },
  /** On a headset, playing flat in the browser window instead of in XR. */
  window: 'THIS WINDOW',
  language: 'LANGUAGE',
  accessibility: 'ACCESSIBILITY',
  bigNumbers: (on: boolean) => `BIG NUMBERS: ${on ? 'ON' : 'OFF'}`,
  access: { noTimer: 'NO TIMER', contrast: 'HIGH CONTRAST', readAloud: 'READ ALOUD', steadyAim: 'STEADY AIM' } as Record<Access, string>,
  onOff: (on: boolean): string => (on ? 'ON' : 'OFF'),
  sound: (on: boolean) => `SOUND: ${on ? 'ON' : 'OFF'}`,
  music: (on: boolean) => `MUSIC: ${on ? 'ON' : 'OFF'}`,
  howtoAgain: 'SHOW THE HOW-TO AGAIN',
  howtoReset: 'Done. The paper hand will show each game again the next time it comes up.',
  hint: {
    computer: 'Pick where you play first. This computer plays with the mouse; the headset opens the game on your real desk.',
    xr: 'The game opens on your real desk. Put the headset on and play with your hands.',
    smartboard: 'Touch the big screen to play. RACE ON THE SMARTBOARD puts three players side by side.',
  },
  /** The hint on a headset, where the controller's ray and trigger pick on this page. */
  hintHeadset: {
    xr: 'Point the controller and pull the trigger to pick. The game then opens in XR on your real desk.',
    computer: 'The game plays flat in this window. Point the controller and pull the trigger to pick.',
  },
  noXr: 'No headset found on this device',
  noXrBody:
    'This device has no headset ready for the game. Open numeria.eziedutech.dev in the browser of a Meta Quest headset to play on your real desk, or play here on this computer.',
  play: 'PLAY',
  you: 'YOU',
  practice: ['PRACTICE ON MY OWN', 'No timer, your own pace'],
  robots: ['RACE THE ROBOTS', 'Two robot rivals, 3 timed waves'],
  /** A race left before its results, picked up again from round `n` (the boss when `boss`). */
  resumeSub: (n: number, boss: boolean) => (boss ? 'Carry on from the boss round' : `Carry on from wave ${n}`),
  resumeBody: (n: number, boss: boolean) =>
    `Your last race stopped before ${boss ? 'the boss round' : `wave ${n}`}. Carry on from there, or start a new race.`,
  resumeGo: (n: number, boss: boolean) => (boss ? 'CARRY ON: BOSS ROUND' : `CARRY ON: WAVE ${n}`),
  startOver: 'START A NEW RACE',
  classmates: ['RACE MY CLASSMATES', 'Same class, real time'],
  rival: ['FIND A RIVAL', 'A student of your grade, or a robot'],
  rivalFinding: 'Looking for a rival...',
  lobbyRival: (s: number) => `Looking for a rival in your grade. If nobody comes, a robot races you in ${s} s.`,
  smartboard: ['RACE ON THE SMARTBOARD', 'Three players, one big screen'],
  studentFirst: 'Enter your student code first',
  student: ["I'M IN A CLASS", 'Class code, seat and pictures'],
  teacher: ['TEACHER SIGN IN', 'Classes, rooms and reports'],
  tips: ['MATH EDU', 'Paper lessons for grade 4 to 6'],
  watch: ['WATCH A MATCH', 'With a watch code, or the demo match'],
  town: ['MY FOLD TOWN', 'Build your town with the Folds you earn'],
  board: ['LEADERBOARD', 'My class and the world'],
  soon: 'SOON',
  footer: ['How to play', 'For parents', 'Privacy', 'Credits and licenses', 'About'],
  fullPolicy: 'Read the full privacy policy and how to delete data',
  close: 'CLOSE',
  cancel: 'CANCEL',
  go: 'GO',
  roomClosed: 'The room is closed.',
  turnOver: "Your group's turn is over: the teacher called the next group.",
  lobbyGroup: (g: string) => ` Group ${g}'s turn.`,
  roomCode: 'Room code (on the class screen)',
  joining: 'Joining the room...',
  lobbyTitle: 'RACE ROOM',
  lobbyYou: (name: string) => `You are ${name}.`,
  lobbySeats: (n: number, of: number) => `${n} of ${of} seats taken. Robots fill the empty seats.`,
  lobbyIn: 'In the room',
  lobbyWait: 'Your teacher starts the match from the class screen. Then every desk counts down together.',
  lobbyReadyWait: (n: number, of: number) => `${n} of ${of} ready. It starts when everyone is ready.`,
  lobbyReady: "I'M READY",
  lobbyOn: 'The match is on.',
  toDesk: 'TO MY DESK NOW',
  waitAtDesk: 'WAIT AT MY DESK',
  deskEarly: 'You may wait at your desk. No creature comes before the countdown ends, for anyone.',
  lobbyStarting: (s: number) => `The match starts in ${s}. Go to your desk now!`,
  watchCode: 'Watch code (on the class screen)',
  watchDemo: 'WATCH THE DEMO MATCH',
  joinClassRoom: (label: string) => `JOIN ${label.toUpperCase()}'S ROOM`,
  noClassRoom: (label: string) => `No race room is active for ${label} yet. Wait for your teacher, or type a code.`,
  orTypeCode: 'Or type a room code',
  classCode: '1. Class code (on your card or the class screen)',
  seat: '2. Your seat number',
  tens: 'Tens',
  ones: 'Ones',
  seatIs: 'Seat',
  picture: '3. Your 3 pictures, in the order on your card',
  pictureNames: ['SUN', 'MOON', 'STAR', 'HEART', 'TREE', 'FISH', 'HOUSE', 'BOAT', 'FLOWER'],
  undoPicture: 'UNDO',
  studentHi: (name: string) => `HI, ${name.toUpperCase()}`,
  studentSeat: (label: string, seat: number) => `${label} · Seat ${String(seat).padStart(2, '0')}`,
  seatNo: (seat: number) => `SEAT ${String(seat).padStart(2, '0')}`,
  hello: 'HI!',
  inClass: 'IN CLASS',
  studentWelcome: 'You are in your class seat. This device remembers it for 30 days. On a shared headset, sign out when you finish.',
  studentKept: 'This device is in your class seat. On a shared headset, sign out when you finish.',
  teacherOff: 'Teacher sign-in is not set up in this copy of the game. Use the teacher page on the Numeria Arena site.',
  teacherIntro: 'For teachers and club organisers. Students never sign in here.',
  /** Shown on the home page while there is no network. */
  offline: 'OFFLINE: RESULTS KEPT ON THIS DEVICE',
  offlineSignIn: 'Signing in needs the internet. Practice and robot races work offline, and their results wait on this device.',
  google: 'Continue with Google',
  facebook: 'Continue with Facebook',
  email: 'EMAIL ME A SIGN-IN LINK',
  emailLabel: 'Your email',
  sendLink: 'SEND THE LINK',
  linkSent: (email: string) => `A sign-in link is on its way to ${email}. Open it in this browser to finish signing in.`,
  confirmEmail: 'This link was opened in another browser. Type the email it was sent to.',
  signingIn: 'Signing in',
  serverAway: 'Server out of reach',
  signInAgain: 'Sign in again',
  signOut: 'SIGN OUT',
  myClasses: ['MY CLASSES', 'Class codes and seats'],
  teach: 'TEACH',
  tryPractice: ['TRY: PRACTICE', 'What your students play, no timer'],
  tryRobots: ['TRY: RACE THE ROBOTS', 'The race your students run'],
  openRoom: ['NEW RACE ROOM', 'For a class, or open to anyone'],
  history: ['ROOMS SO FAR', 'Each room and its results'],
  status: { pending: 'Waiting for approval', approved: 'Approved', suspended: 'Suspended' },
  pendingBody: 'An admin checks new organizers. Until then you can set up one trial class with 5 seats and robots.',
  finishSignUp: 'Finish signing up',
  regTitle: 'ABOUT YOU',
  regIntro: 'One time only. Students never see your email.',
  yourName: 'Your name (shown to your classes)',
  orgName: 'School or club (leave empty for a personal workspace)',
  orgKind: 'Kind',
  kinds: { school: 'SCHOOL', tutoring: 'TUTORING', community: 'COMMUNITY', event: 'EVENT' },
  country: 'Country (2 letters, like ID or US)',
  statement:
    'I am a teacher or organizer responsible for the children in my groups, and I will get parental permission as my local rules require.',
  account: 'TEACHER ACCOUNT',
  manageLink: 'Open the teacher page on this site',
  manageInstead: 'Or open the full teacher page',
  teacherPage: 'Teacher page',
  errors: {
    'auth/popup-closed-by-user': 'The sign-in window was closed before it finished.',
    'auth/cancelled-popup-request': 'The sign-in window was closed before it finished.',
    'auth/popup-blocked': 'The browser blocked the sign-in window. Allow pop-ups for this page and try again.',
    'auth/account-exists-with-different-credential': 'This email already signs in another way. Use that way first.',
    'auth/invalid-email': 'That email does not look right.',
    'auth/invalid-action-code': 'This sign-in link was used or has expired. Ask for a new one.',
    offline: 'The class server cannot be reached right now. Practice and robot races still work.',
    invalid_token: 'The sign-in could not be checked. Sign out and try again.',
    email_required: 'This account has no email. Use Google or an email link instead.',
    suspended: 'This account is suspended. Contact the Numeria Arena team.',
    auth_unavailable: 'Sign-in checks are down for a moment. Try again shortly.',
    name: 'Write a name of 2 to 60 letters.',
    org_name: 'The school or club name is too long.',
    org_kind: 'Pick a kind.',
    country: 'Write the country as two letters, like ID.',
    terms_not_agreed: 'Tick the statement to continue.',
    terms_changed: 'The statement changed. Reload the page and try again.',
    already_registered: 'This account is already signed up.',
    room_not_found: 'No room has that code. Check the class screen.',
    room_full: 'This room is full.',
    class_only: "This room is for one class. Sign in to your seat first: I'M IN A CLASS.",
    students_only: "FIND A RIVAL is for students in a class seat. Sign in to your seat first: I'M IN A CLASS.",
    wrong_class: 'This room is for another class.',
    not_your_turn: "It is another group's turn. Watch the class screen; your group is called later.",
    match_started: 'This match has already started.',
    starting: 'The countdown is already on.',
    watch_code: 'That is a watch code. Use it under WATCH A MATCH.',
    code_length: 'Write all 6 letters of the code.',
    seat_pick: 'Tap your seat number: tens, then ones.',
    picture: 'Tap your 3 pictures, in the order on your card.',
    class_not_found: 'No class has that code. Check your card.',
    seat_not_found: 'That seat is not in this class. Check your card.',
    wrong_picture: 'Those pictures are not right. Look at your card and tap them in order.',
    locked: 'Too many tries. Wait 5 minutes, then try again.',
    ask_teacher: 'This seat is locked. Ask your teacher to open it.',
    class_paused: 'Too many wrong tries in this class. Wait a few minutes.',
    signed_out: 'Sign in again, then try once more.',
    organizer_required: 'Finish the teacher sign-up first.',
    other: 'Something went wrong. Try again.',
  } as Record<string, string>,
  soonBody: {
    accessibility:
      'Big numbers make questions and answers larger. No timer hides the answer clock and the speed bonus (a race keeps its waves). High contrast puts light letters on dark cards and pages. Read aloud speaks each question. Steady aim calms a shaky pointer in the headset. Every game can be played with one hand.',
  },
  pages: {
    'How to play':
      'Pick PRACTICE ON MY OWN or RACE THE ROBOTS. A paper animal walks out of the book with a question. Pop the balloon with the right answer, or join two crystals that make the number it asks for. Right answers send it home happy. Every play earns Folds to build MY FOLD TOWN: practice and robot races give up to 100 Folds a day; class races, rooms and FIND A RIVAL have no limit. Each topic you master raises a landmark in your town.',
    'For parents':
      'Children play without an account. Progress stays on this device. When a teacher sets up a class, children sign in with a class code and a picture password, never with a name or an email. Teachers see only their own class.',
    Privacy:
      'We keep as little as we can. Without a class, nothing leaves this device. With a class, the server keeps a made-up player name (like BLUE CRANE 07) and the answers given, never a real name, email, photo, voice, or what the headset cameras see. Teachers who sign in share their name and email so we can run their classes.',
    'Credits and licenses':
      'Built with the Immersive Web SDK (MIT) and three.js (MIT). Paper animals, letters and pictures are made by the project owner. The background music was made by the project owner with an AI music tool. Every third-party part is listed with its license in the source repository.',
    About: 'Numeria Arena is a mixed reality maths game for children aged 10 to 12: a pop-up book opens on your real desk and paper animals bring you questions.',
  },
};

const ID: typeof EN = {
  playOn: 'MAIN DI',
  device: { computer: 'KOMPUTER INI', xr: 'META QUEST (XR)', smartboard: 'SMARTBOARD' },
  window: 'JENDELA INI',
  language: 'BAHASA',
  accessibility: 'AKSESIBILITAS',
  bigNumbers: (on: boolean) => `ANGKA BESAR: ${on ? 'NYALA' : 'MATI'}`,
  access: { noTimer: 'TANPA WAKTU', contrast: 'KONTRAS TINGGI', readAloud: 'BACAKAN SOAL', steadyAim: 'BIDIKAN STABIL' } as Record<Access, string>,
  onOff: (on: boolean) => (on ? 'NYALA' : 'MATI'),
  sound: (on: boolean) => `SUARA: ${on ? 'NYALA' : 'MATI'}`,
  music: (on: boolean) => `MUSIK: ${on ? 'NYALA' : 'MATI'}`,
  howtoAgain: 'TAMPILKAN PETUNJUK LAGI',
  howtoReset: 'Selesai. Tangan kertas akan memperagakan setiap game lagi saat game itu muncul.',
  hint: {
    computer: 'Pilih dulu tempat bermain. Komputer ini dimainkan dengan mouse; headset membuka game di mejamu sendiri.',
    xr: 'Game terbuka di mejamu sendiri. Pakai headset dan bermain dengan tangan.',
    smartboard: 'Sentuh layar besar untuk bermain. BALAPAN DI SMARTBOARD menjajarkan tiga pemain.',
  },
  hintHeadset: {
    xr: 'Arahkan controller, lalu tekan pelatuk untuk memilih. Game lalu terbuka di XR di mejamu sendiri.',
    computer: 'Game dimainkan datar di jendela ini. Arahkan controller, lalu tekan pelatuk untuk memilih.',
  },
  noXr: 'Headset tidak ditemukan di perangkat ini',
  noXrBody:
    'Perangkat ini tidak punya headset yang siap untuk game. Buka numeria.eziedutech.dev di browser headset Meta Quest untuk bermain di mejamu sendiri, atau bermain di komputer ini.',
  play: 'MAIN',
  you: 'KAMU',
  practice: ['BERLATIH SENDIRI', 'Tanpa waktu, sesuai kecepatanmu'],
  robots: ['LOMBA LAWAN ROBOT', 'Dua robot, 3 gelombang berwaktu'],
  resumeSub: (n: number, boss: boolean) => (boss ? 'Lanjutkan dari ronde boss' : `Lanjutkan dari gelombang ${n}`),
  resumeBody: (n: number, boss: boolean) =>
    `Lombamu tadi berhenti sebelum ${boss ? 'ronde boss' : `gelombang ${n}`}. Lanjutkan dari situ, atau mulai lomba baru.`,
  resumeGo: (n: number, boss: boolean) => (boss ? 'LANJUTKAN: RONDE BOSS' : `LANJUTKAN: GELOMBANG ${n}`),
  startOver: 'MULAI LOMBA BARU',
  classmates: ['LOMBA DENGAN TEMAN', 'Satu kelas, langsung'],
  rival: ['CARI LAWAN', 'Siswa satu tingkat, atau robot'],
  rivalFinding: 'Mencari lawan...',
  lobbyRival: (s: number) => `Mencari lawan satu tingkat. Kalau tidak ada yang datang, robot melawanmu dalam ${s} detik.`,
  smartboard: ['BALAPAN DI SMARTBOARD', 'Tiga pemain, satu layar besar'],
  studentFirst: 'Masukkan kode siswa dulu',
  student: ['AKU DI KELAS', 'Kode kelas, kursi, dan gambar'],
  teacher: ['MASUK SEBAGAI GURU', 'Kelas, ruang main, dan laporan'],
  tips: ['MATH EDU', 'Pelajaran kertas kelas 4 sampai 6'],
  watch: ['TONTON PERTANDINGAN', 'Dengan kode tonton, atau pertandingan demo'],
  town: ['KOTA LIPATKU', 'Bangun kotamu dengan Folds yang kamu dapat'],
  board: ['PAPAN PERINGKAT', 'Kelasku dan seluruh dunia'],
  soon: 'SEGERA',
  footer: ['Cara bermain', 'Untuk orang tua', 'Privasi', 'Kredit dan lisensi', 'Tentang'],
  fullPolicy: 'Baca kebijakan privasi lengkap dan cara menghapus data',
  close: 'TUTUP',
  cancel: 'BATAL',
  go: 'MASUK',
  roomClosed: 'Ruang sudah ditutup.',
  turnOver: 'Giliran kelompokmu selesai: guru memanggil kelompok berikutnya.',
  lobbyGroup: (g: string) => ` Giliran kelompok ${g}.`,
  history: ['RUANG SEBELUMNYA', 'Tiap ruang dan hasilnya'],
  roomCode: 'Kode ruang (di layar kelas)',
  joining: 'Menyambung ke ruang...',
  lobbyTitle: 'RUANG LOMBA',
  lobbyYou: (name: string) => `Kamu adalah ${name}.`,
  lobbySeats: (n: number, of: number) => `${n} dari ${of} kursi terisi. Robot mengisi kursi kosong.`,
  lobbyIn: 'Di ruang ini',
  lobbyWait: 'Gurumu memulai pertandingan dari layar kelas. Lalu semua meja menghitung mundur bersama.',
  lobbyReadyWait: (n: number, of: number) => `${n} dari ${of} siap. Mulai saat semua siap.`,
  lobbyReady: 'AKU SIAP',
  lobbyOn: 'Pertandingan sedang berjalan.',
  toDesk: 'KE MEJAKU SEKARANG',
  waitAtDesk: 'TUNGGU DI MEJAKU',
  deskEarly: 'Kamu boleh menunggu di meja. Belum ada soal sebelum hitung mundur selesai, untuk siapa pun.',
  lobbyStarting: (s: number) => `Pertandingan mulai dalam ${s}. Ke mejamu sekarang!`,
  watchCode: 'Kode tonton (di layar kelas)',
  watchDemo: 'TONTON PERTANDINGAN DEMO',
  joinClassRoom: (label: string) => `GABUNG KE RUANG ${label.toUpperCase()}`,
  noClassRoom: (label: string) => `Belum ada ruang lomba yang aktif untuk ${label}. Tunggu gurumu, atau ketik kode.`,
  orTypeCode: 'Atau ketik kode ruang',
  classCode: '1. Kode kelas (di kartumu atau di layar kelas)',
  seat: '2. Nomor kursimu',
  tens: 'Puluhan',
  ones: 'Satuan',
  seatIs: 'Kursi',
  picture: '3. Tiga gambarmu, urut seperti di kartumu',
  pictureNames: ['MATAHARI', 'BULAN', 'BINTANG', 'HATI', 'POHON', 'IKAN', 'RUMAH', 'PERAHU', 'BUNGA'],
  undoPicture: 'HAPUS SATU',
  studentHi: (name: string) => `HAI, ${name.toUpperCase()}`,
  studentSeat: (label: string, seat: number) => `${label} · Kursi ${String(seat).padStart(2, '0')}`,
  seatNo: (seat: number) => `KURSI ${String(seat).padStart(2, '0')}`,
  hello: 'HAI!',
  inClass: 'DI KELAS',
  studentWelcome: 'Kamu sudah duduk di kursi kelasmu. Perangkat ini mengingatnya 30 hari. Di headset bersama, keluar setelah selesai.',
  studentKept: 'Perangkat ini ada di kursi kelasmu. Di headset bersama, keluar setelah selesai.',
  teacherOff: 'Masuk guru belum disiapkan di salinan game ini. Pakai halaman guru di situs Numeria Arena.',
  teacherIntro: 'Untuk guru dan pembina klub. Siswa tidak pernah masuk di sini.',
  offline: 'OFFLINE: HASIL DISIMPAN DI PERANGKAT',
  offlineSignIn: 'Masuk membutuhkan internet. Berlatih dan lomba lawan robot tetap bisa tanpa internet, dan hasilnya menunggu di perangkat ini.',
  google: 'Lanjut dengan Google',
  facebook: 'Lanjut dengan Facebook',
  email: 'KIRIM TAUTAN MASUK KE EMAIL',
  emailLabel: 'Email Anda',
  sendLink: 'KIRIM TAUTAN',
  linkSent: (email: string) => `Tautan masuk sedang dikirim ke ${email}. Buka di browser ini untuk menyelesaikan masuk.`,
  confirmEmail: 'Tautan ini dibuka di browser lain. Ketik email tujuan tautan itu.',
  signingIn: 'Sedang masuk',
  serverAway: 'Server belum terhubung',
  signInAgain: 'Masuk lagi',
  signOut: 'KELUAR',
  myClasses: ['KELAS SAYA', 'Kode kelas dan kursi'],
  teach: 'MENGAJAR',
  tryPractice: ['COBA: LATIHAN', 'Yang dimainkan siswa, tanpa waktu'],
  tryRobots: ['COBA: LOMBA LAWAN ROBOT', 'Lomba yang dijalani siswa'],
  openRoom: ['BUAT RUANG LOMBA', 'Untuk satu kelas, atau terbuka untuk siapa saja'],
  status: { pending: 'Menunggu persetujuan', approved: 'Disetujui', suspended: 'Ditangguhkan' },
  pendingBody: 'Admin memeriksa penyelenggara baru. Sambil menunggu, Anda bisa menyiapkan satu kelas percobaan dengan 5 kursi dan robot.',
  finishSignUp: 'Selesaikan pendaftaran',
  regTitle: 'TENTANG ANDA',
  regIntro: 'Hanya sekali. Siswa tidak pernah melihat email Anda.',
  yourName: 'Nama Anda (tampil di kelas Anda)',
  orgName: 'Sekolah atau klub (kosongkan untuk ruang kerja pribadi)',
  orgKind: 'Jenis',
  kinds: { school: 'SEKOLAH', tutoring: 'BIMBEL', community: 'KOMUNITAS', event: 'ACARA' },
  country: 'Negara (2 huruf, misalnya ID atau US)',
  statement:
    'Saya guru atau penyelenggara yang bertanggung jawab atas anak-anak di grup saya, dan akan meminta izin orang tua sesuai aturan setempat.',
  account: 'AKUN GURU',
  manageLink: 'Buka halaman guru di situs ini',
  manageInstead: 'Atau buka halaman guru lengkap',
  teacherPage: 'Halaman guru',
  errors: {
    'auth/popup-closed-by-user': 'Jendela masuk ditutup sebelum selesai.',
    'auth/cancelled-popup-request': 'Jendela masuk ditutup sebelum selesai.',
    'auth/popup-blocked': 'Browser memblokir jendela masuk. Izinkan pop-up untuk halaman ini lalu coba lagi.',
    'auth/account-exists-with-different-credential': 'Email ini sudah masuk dengan cara lain. Pakai cara itu dulu.',
    'auth/invalid-email': 'Email itu sepertinya keliru.',
    'auth/invalid-action-code': 'Tautan masuk ini sudah dipakai atau kedaluwarsa. Minta tautan baru.',
    offline: 'Server kelas belum bisa dihubungi. Latihan dan lomba robot tetap bisa dimainkan.',
    invalid_token: 'Masuk tidak bisa diperiksa. Keluar lalu coba lagi.',
    email_required: 'Akun ini tidak punya email. Pakai Google atau tautan email.',
    suspended: 'Akun ini ditangguhkan. Hubungi tim Numeria Arena.',
    auth_unavailable: 'Pemeriksaan masuk sedang terganggu. Coba lagi sebentar lagi.',
    name: 'Tulis nama 2 sampai 60 huruf.',
    org_name: 'Nama sekolah atau klub terlalu panjang.',
    org_kind: 'Pilih jenisnya.',
    country: 'Tulis negara dengan dua huruf, misalnya ID.',
    terms_not_agreed: 'Centang pernyataan untuk melanjutkan.',
    terms_changed: 'Pernyataan berubah. Muat ulang halaman lalu coba lagi.',
    already_registered: 'Akun ini sudah terdaftar.',
    room_not_found: 'Tidak ada ruang dengan kode itu. Periksa layar kelas.',
    room_full: 'Ruang ini sudah penuh.',
    class_only: 'Ruang ini untuk satu kelas. Masuk ke kursimu dulu: AKU DI KELAS.',
    students_only: 'CARI LAWAN untuk siswa yang punya kursi di kelas. Masuk ke kursimu dulu: AKU DI KELAS.',
    wrong_class: 'Ruang ini untuk kelas lain.',
    not_your_turn: 'Sekarang giliran kelompok lain. Lihat layar kelas; kelompokmu dipanggil nanti.',
    match_started: 'Pertandingan ini sudah dimulai.',
    starting: 'Hitung mundur sudah berjalan.',
    watch_code: 'Itu kode tonton. Pakai di TONTON PERTANDINGAN.',
    code_length: 'Tulis keenam huruf kodenya.',
    seat_pick: 'Tekan nomor kursimu: puluhan, lalu satuan.',
    picture: 'Tekan tiga gambarmu, urut seperti di kartumu.',
    class_not_found: 'Tidak ada kelas dengan kode itu. Periksa kartumu.',
    seat_not_found: 'Kursi itu tidak ada di kelas ini. Periksa kartumu.',
    wrong_picture: 'Gambarnya belum tepat. Lihat kartumu lalu tekan urut.',
    locked: 'Terlalu banyak percobaan. Tunggu 5 menit, lalu coba lagi.',
    ask_teacher: 'Kursi ini terkunci. Minta gurumu membukanya.',
    class_paused: 'Terlalu banyak percobaan salah di kelas ini. Tunggu beberapa menit.',
    signed_out: 'Masuk lagi, lalu coba sekali lagi.',
    organizer_required: 'Selesaikan pendaftaran guru dulu.',
    other: 'Ada yang salah. Coba lagi.',
  } as Record<string, string>,
  soonBody: {
    accessibility:
      'Angka besar membuat soal dan jawaban lebih besar. Tanpa waktu menyembunyikan jam jawaban dan bonus kecepatan (lomba tetap punya gelombangnya). Kontras tinggi memberi huruf terang di kartu dan halaman gelap. Bacakan soal membacakan tiap soal. Bidikan stabil menenangkan penunjuk yang goyang di headset. Semua game bisa dimainkan dengan satu tangan.',
  },
  pages: {
    'How to play':
      'Pilih BERLATIH SENDIRI atau LOMBA LAWAN ROBOT. Hewan kertas keluar dari buku membawa soal. Pecahkan balon berisi jawaban yang benar, atau gabungkan dua kristal yang hasilnya sama dengan angka yang diminta. Jawaban benar membuatnya pulang dengan gembira. Setiap permainan memberi Folds untuk membangun KOTA LIPATKU: latihan dan lomba robot memberi paling banyak 100 Folds sehari; lomba kelas, ruang, dan CARI LAWAN tanpa batas. Setiap topik yang kamu kuasai mendirikan satu landmark di kotamu.',
    'For parents':
      'Anak bermain tanpa akun. Progres tersimpan di perangkat ini. Bila guru membuat kelas, anak masuk dengan kode kelas dan sandi gambar, tidak pernah dengan nama atau email. Guru hanya melihat kelasnya sendiri.',
    Privacy:
      'Kami menyimpan sesedikit mungkin. Tanpa kelas, tidak ada data yang keluar dari perangkat ini. Dengan kelas, server menyimpan nama pemain samaran (misalnya BLUE CRANE 07) dan jawaban, tidak pernah nama asli, email, foto, suara, atau apa yang dilihat kamera headset. Guru yang masuk memberikan nama dan email agar kami bisa menjalankan kelasnya.',
    'Credits and licenses':
      'Dibangun dengan Immersive Web SDK (MIT) dan three.js (MIT). Hewan kertas, huruf, dan gambar dibuat oleh pemilik proyek. Musik latarnya dibuat oleh pemilik proyek dengan alat musik AI. Setiap bagian pihak ketiga tercatat bersama lisensinya di repositori sumber.',
    About: 'Numeria Arena adalah game matematika mixed reality untuk anak 10 sampai 12 tahun: buku pop-up terbuka di mejamu dan hewan kertas membawakan soal.',
  },
};

export const HOME_TEXT: Record<Lang, typeof EN> = { en: EN, id: ID };
export type HomeText = typeof EN;
