/**
 * Text of the home page in English (default) and Indonesian. Headings and
 * card titles are capitals, drawn with the paper letters.
 */
export type Lang = 'en' | 'id';

const EN = {
  playOn: 'PLAY ON',
  device: { computer: 'THIS COMPUTER', xr: 'HEADSET (XR)', smartboard: 'SMARTBOARD' },
  language: 'LANGUAGE',
  accessibility: 'ACCESSIBILITY',
  bigNumbers: (on: boolean) => `BIG NUMBERS: ${on ? 'ON' : 'OFF'}`,
  howtoAgain: 'SHOW THE HOW-TO AGAIN',
  howtoReset: 'Done. The paper hand will show each game again the next time it comes up.',
  hint: {
    computer: 'Pick where you play first. This computer plays with the mouse; the headset opens the game on your real desk.',
    xr: 'The game opens on your real desk. Put the headset on and play with your hands.',
    smartboard: 'Touch the big screen to play. The class helper mode for smartboards is coming soon.',
  },
  noXr: 'No headset found on this device',
  play: 'PLAY',
  you: 'YOU',
  practice: ['PRACTICE ON MY OWN', 'No timer, your own pace'],
  robots: ['RACE THE ROBOTS', 'Two robot rivals, 3 timed waves'],
  classmates: ['RACE MY CLASSMATES', 'Same class, real time'],
  smartboard: ['PLAY ON THE SMARTBOARD', 'Help the headset players as a class'],
  studentFirst: 'Enter your student code first',
  student: ['ENTER STUDENT CODE', 'Class code, seat and picture password'],
  teacher: ['TEACHER SIGN IN', 'Classes, rooms and reports'],
  tips: ['MATH TIPS', 'Ways to understand primary maths'],
  watch: ['WATCH A MATCH', 'With a watch code, or the demo match'],
  town: ['MY FOLD TOWN', 'Build your town with the Folds you earn'],
  board: ['LEADERBOARD', 'My class and the world'],
  soon: 'SOON',
  footer: ['How to play', 'For parents', 'Privacy', 'Credits and licenses', 'About'],
  fullPolicy: 'Read the full privacy policy and how to delete data',
  close: 'CLOSE',
  cancel: 'CANCEL',
  go: 'GO',
  classCode: '1. Class code (on your card or the class screen)',
  seat: '2. Your seat number',
  tens: 'Tens',
  ones: 'Ones',
  seatIs: 'Seat',
  picture: '3. Your picture password (3 pictures)',
  serverSoon:
    'Class sign-in opens when the class server is ready. Until then you can practise and race the robots without signing in.',
  teacherIntro: 'For teachers and club organisers. Students never sign in here.',
  google: 'Continue with Google',
  facebook: 'Continue with Facebook',
  email: 'EMAIL ME A SIGN-IN LINK',
  emailLabel: 'Your email',
  sendLink: 'SEND THE LINK',
  linkSent: (email: string) => `A sign-in link is on its way to ${email}. Open it in this browser to finish signing in.`,
  confirmEmail: 'This link was opened in another browser. Type the email it was sent to.',
  signingIn: 'Signing in',
  signOut: 'SIGN OUT',
  myClasses: ['MY CLASSES', 'Seats, cards, reports'],
  openRoom: ['OPEN A CLASS ROOM', 'Room code on the class screen'],
  classesSoon: 'Classes, seats and class rooms open in the next update of the class server. Your account is ready for them.',
  status: { pending: 'Waiting for approval', approved: 'Approved', suspended: 'Suspended' },
  pendingBody: 'An admin checks new organizers. Until then you can set up one trial class with 5 seats and robots.',
  finishSignUp: 'Finish signing up',
  regTitle: 'ABOUT YOU',
  regIntro: 'One time only. Students never see your email.',
  yourName: 'Your name (shown to your classes)',
  orgName: 'School or club (leave empty for a personal workspace)',
  orgKind: 'Kind',
  kinds: { school: 'SCHOOL', tutoring: 'TUTORING', community: 'COMMUNITY', event: 'EVENT' },
  country: 'Country (2 letters, like ID or US)',
  statement:
    'I am a teacher or organizer responsible for the children in my groups, and I will get parental permission as my local rules require.',
  account: 'TEACHER ACCOUNT',
  errors: {
    'auth/popup-closed-by-user': 'The sign-in window was closed before it finished.',
    'auth/cancelled-popup-request': 'The sign-in window was closed before it finished.',
    'auth/popup-blocked': 'The browser blocked the sign-in window. Allow pop-ups for this page and try again.',
    'auth/account-exists-with-different-credential': 'This email already signs in another way. Use that way first.',
    'auth/invalid-email': 'That email does not look right.',
    'auth/invalid-action-code': 'This sign-in link was used or has expired. Ask for a new one.',
    offline: 'The class server cannot be reached right now. Practice and robot races still work.',
    invalid_token: 'The sign-in could not be checked. Sign out and try again.',
    email_required: 'This account has no email. Use Google or an email link instead.',
    suspended: 'This account is suspended. Contact the Numeria Arena team.',
    auth_unavailable: 'Sign-in checks are down for a moment. Try again shortly.',
    name: 'Write a name of 2 to 60 letters.',
    org_name: 'The school or club name is too long.',
    org_kind: 'Pick a kind.',
    country: 'Write the country as two letters, like ID.',
    terms_not_agreed: 'Tick the statement to continue.',
    terms_changed: 'The statement changed. Reload the page and try again.',
    already_registered: 'This account is already signed up.',
    other: 'Something went wrong. Try again.',
  } as Record<string, string>,
  soonBody: {
    tips: 'Short lessons and tips for every topic in the game are on their way.',
    board:
      'Two boards: MY CLASS and GLOBAL. Each ranks HIGH STRIKE (the best race scores) and CITY BUILDER (the biggest Fold Towns), for this month or for all time. Players show only as made-up names, like BLUE CRANE 07.',
    town: 'Every right answer earns Folds. Soon you will spend them on paper houses, trees and bridges, and unlock a landmark for every topic you master.',
    watch: 'Watching a class match with a watch code, and the always-on demo match, come with the class server.',
    smartboard: 'On a smartboard the whole class helps the headset players. This mode is coming in a later update.',
    accessibility:
      'Big numbers make questions and answers larger. Coming next: no timer, high contrast, read the question aloud, and steadier aim. Every game can already be played with one hand.',
  },
  pages: {
    'How to play':
      'Pick PRACTICE ON MY OWN or RACE THE ROBOTS. A paper animal walks out of the book with a question. Pop the balloon with the right answer, or join two crystals that make the number it asks for. Right answers send it home happy.',
    'For parents':
      'Children play without an account. Progress stays on this device. When a teacher sets up a class, children sign in with a class code and a picture password, never with a name or an email. Teachers see only their own class.',
    Privacy:
      'We keep as little as we can. Without a class, nothing leaves this device. With a class, the server keeps a made-up player name (like BLUE CRANE 07) and the answers given, never a real name, email, photo, voice, or what the headset cameras see. Teachers who sign in share their name and email so we can run their classes.',
    'Credits and licenses':
      'Built with the Immersive Web SDK (MIT) and three.js (MIT). Paper animals, letters and pictures are made by the project owner. Every third-party part is listed with its license in the source repository.',
    About: 'Numeria Arena is a mixed reality maths game for children aged 10 to 12: a pop-up book opens on your real desk and paper animals bring you questions.',
  },
};

const ID: typeof EN = {
  playOn: 'MAIN DI',
  device: { computer: 'KOMPUTER INI', xr: 'HEADSET (XR)', smartboard: 'SMARTBOARD' },
  language: 'BAHASA',
  accessibility: 'AKSESIBILITAS',
  bigNumbers: (on: boolean) => `ANGKA BESAR: ${on ? 'NYALA' : 'MATI'}`,
  howtoAgain: 'TAMPILKAN PETUNJUK LAGI',
  howtoReset: 'Selesai. Tangan kertas akan memperagakan setiap game lagi saat game itu muncul.',
  hint: {
    computer: 'Pilih dulu tempat bermain. Komputer ini dimainkan dengan mouse; headset membuka game di mejamu sendiri.',
    xr: 'Game terbuka di mejamu sendiri. Pakai headset dan bermain dengan tangan.',
    smartboard: 'Sentuh layar besar untuk bermain. Mode pembantu kelas untuk smartboard segera hadir.',
  },
  noXr: 'Headset tidak ditemukan di perangkat ini',
  play: 'MAIN',
  you: 'KAMU',
  practice: ['BERLATIH SENDIRI', 'Tanpa waktu, sesuai kecepatanmu'],
  robots: ['LOMBA LAWAN ROBOT', 'Dua robot, 3 gelombang berwaktu'],
  classmates: ['LOMBA DENGAN TEMAN', 'Satu kelas, langsung'],
  smartboard: ['MAIN DI SMARTBOARD', 'Bantu pemain headset bersama kelas'],
  studentFirst: 'Masukkan kode siswa dulu',
  student: ['MASUKKAN KODE SISWA', 'Kode kelas, kursi, dan sandi gambar'],
  teacher: ['MASUK SEBAGAI GURU', 'Kelas, ruang main, dan laporan'],
  tips: ['TIPS MATEMATIKA', 'Cara memahami matematika SD'],
  watch: ['TONTON PERTANDINGAN', 'Dengan kode tonton, atau pertandingan demo'],
  town: ['KOTA LIPATKU', 'Bangun kotamu dengan Folds yang kamu dapat'],
  board: ['PAPAN PERINGKAT', 'Kelasku dan seluruh dunia'],
  soon: 'SEGERA',
  footer: ['Cara bermain', 'Untuk orang tua', 'Privasi', 'Kredit dan lisensi', 'Tentang'],
  fullPolicy: 'Baca kebijakan privasi lengkap dan cara menghapus data',
  close: 'TUTUP',
  cancel: 'BATAL',
  go: 'MASUK',
  classCode: '1. Kode kelas (di kartumu atau di layar kelas)',
  seat: '2. Nomor kursimu',
  tens: 'Puluhan',
  ones: 'Satuan',
  seatIs: 'Kursi',
  picture: '3. Sandi gambarmu (3 gambar)',
  serverSoon:
    'Masuk kelas dibuka saat server kelas siap. Sampai saat itu kamu tetap bisa berlatih dan lomba melawan robot tanpa masuk.',
  teacherIntro: 'Untuk guru dan pembina klub. Siswa tidak pernah masuk di sini.',
  google: 'Lanjut dengan Google',
  facebook: 'Lanjut dengan Facebook',
  email: 'KIRIM TAUTAN MASUK KE EMAIL',
  emailLabel: 'Email Anda',
  sendLink: 'KIRIM TAUTAN',
  linkSent: (email: string) => `Tautan masuk sedang dikirim ke ${email}. Buka di browser ini untuk menyelesaikan masuk.`,
  confirmEmail: 'Tautan ini dibuka di browser lain. Ketik email tujuan tautan itu.',
  signingIn: 'Sedang masuk',
  signOut: 'KELUAR',
  myClasses: ['KELAS SAYA', 'Kursi, kartu, laporan'],
  openRoom: ['BUKA RUANG KELAS', 'Kode ruang di layar kelas'],
  classesSoon: 'Kelas, kursi, dan ruang kelas dibuka di pembaruan server kelas berikutnya. Akun Anda sudah siap.',
  status: { pending: 'Menunggu persetujuan', approved: 'Disetujui', suspended: 'Ditangguhkan' },
  pendingBody: 'Admin memeriksa penyelenggara baru. Sambil menunggu, Anda bisa menyiapkan satu kelas percobaan dengan 5 kursi dan robot.',
  finishSignUp: 'Selesaikan pendaftaran',
  regTitle: 'TENTANG ANDA',
  regIntro: 'Hanya sekali. Siswa tidak pernah melihat email Anda.',
  yourName: 'Nama Anda (tampil di kelas Anda)',
  orgName: 'Sekolah atau klub (kosongkan untuk ruang kerja pribadi)',
  orgKind: 'Jenis',
  kinds: { school: 'SEKOLAH', tutoring: 'BIMBEL', community: 'KOMUNITAS', event: 'ACARA' },
  country: 'Negara (2 huruf, misalnya ID atau US)',
  statement:
    'Saya guru atau penyelenggara yang bertanggung jawab atas anak-anak di grup saya, dan akan meminta izin orang tua sesuai aturan setempat.',
  account: 'AKUN GURU',
  errors: {
    'auth/popup-closed-by-user': 'Jendela masuk ditutup sebelum selesai.',
    'auth/cancelled-popup-request': 'Jendela masuk ditutup sebelum selesai.',
    'auth/popup-blocked': 'Browser memblokir jendela masuk. Izinkan pop-up untuk halaman ini lalu coba lagi.',
    'auth/account-exists-with-different-credential': 'Email ini sudah masuk dengan cara lain. Pakai cara itu dulu.',
    'auth/invalid-email': 'Email itu sepertinya keliru.',
    'auth/invalid-action-code': 'Tautan masuk ini sudah dipakai atau kedaluwarsa. Minta tautan baru.',
    offline: 'Server kelas belum bisa dihubungi. Latihan dan lomba robot tetap bisa dimainkan.',
    invalid_token: 'Masuk tidak bisa diperiksa. Keluar lalu coba lagi.',
    email_required: 'Akun ini tidak punya email. Pakai Google atau tautan email.',
    suspended: 'Akun ini ditangguhkan. Hubungi tim Numeria Arena.',
    auth_unavailable: 'Pemeriksaan masuk sedang terganggu. Coba lagi sebentar lagi.',
    name: 'Tulis nama 2 sampai 60 huruf.',
    org_name: 'Nama sekolah atau klub terlalu panjang.',
    org_kind: 'Pilih jenisnya.',
    country: 'Tulis negara dengan dua huruf, misalnya ID.',
    terms_not_agreed: 'Centang pernyataan untuk melanjutkan.',
    terms_changed: 'Pernyataan berubah. Muat ulang halaman lalu coba lagi.',
    already_registered: 'Akun ini sudah terdaftar.',
    other: 'Ada yang salah. Coba lagi.',
  } as Record<string, string>,
  soonBody: {
    tips: 'Pelajaran singkat dan tips untuk setiap topik di game sedang disiapkan.',
    board:
      'Dua papan: KELASKU dan GLOBAL. Masing-masing memeringkat HIGH STRIKE (skor lomba terbaik) dan CITY BUILDER (Kota Lipat terbesar), untuk bulan ini atau sepanjang masa. Pemain hanya tampil dengan nama samaran, misalnya BLUE CRANE 07.',
    town: 'Setiap jawaban benar memberi Folds. Sebentar lagi kamu bisa membelanjakannya untuk rumah, pohon, dan jembatan kertas, dan membuka landmark untuk setiap topik yang kamu kuasai.',
    watch: 'Menonton pertandingan kelas dengan kode tonton, dan pertandingan demo, hadir bersama server kelas.',
    smartboard: 'Di smartboard, seluruh kelas membantu pemain headset. Mode ini hadir di pembaruan berikutnya.',
    accessibility:
      'Angka besar membuat soal dan jawaban lebih besar. Segera: tanpa waktu, kontras tinggi, soal dibacakan, dan bidikan lebih stabil. Semua game sudah bisa dimainkan dengan satu tangan.',
  },
  pages: {
    'How to play':
      'Pilih BERLATIH SENDIRI atau LOMBA LAWAN ROBOT. Hewan kertas keluar dari buku membawa soal. Pecahkan balon berisi jawaban yang benar, atau gabungkan dua kristal yang hasilnya sama dengan angka yang diminta. Jawaban benar membuatnya pulang dengan gembira.',
    'For parents':
      'Anak bermain tanpa akun. Progres tersimpan di perangkat ini. Bila guru membuat kelas, anak masuk dengan kode kelas dan sandi gambar, tidak pernah dengan nama atau email. Guru hanya melihat kelasnya sendiri.',
    Privacy:
      'Kami menyimpan sesedikit mungkin. Tanpa kelas, tidak ada data yang keluar dari perangkat ini. Dengan kelas, server menyimpan nama pemain samaran (misalnya BLUE CRANE 07) dan jawaban, tidak pernah nama asli, email, foto, suara, atau apa yang dilihat kamera headset. Guru yang masuk memberikan nama dan email agar kami bisa menjalankan kelasnya.',
    'Credits and licenses':
      'Dibangun dengan Immersive Web SDK (MIT) dan three.js (MIT). Hewan kertas, huruf, dan gambar dibuat oleh pemilik proyek. Setiap bagian pihak ketiga tercatat bersama lisensinya di repositori sumber.',
    About: 'Numeria Arena adalah game matematika mixed reality untuk anak 10 sampai 12 tahun: buku pop-up terbuka di mejamu dan hewan kertas membawakan soal.',
  },
};

export const HOME_TEXT: Record<Lang, typeof EN> = { en: EN, id: ID };
export type HomeText = typeof EN;
