server {
    listen 80;
    root /usr/share/nginx/html;
    absolute_redirect off;

    location = /play {
        return 301 /play/;
    }
    location = /play/version.json {
        add_header Cache-Control "no-store";
    }
    location /play/ {
        try_files $uri $uri/ /play/index.html;
    }
}
