/**
 * The shop of Fold Town, by hand: for every piece of the town asset set its
 * group, price in Folds, the buildings standing before it is sold, and its
 * name in English and Indonesian. Footprints, windows and floors come from
 * the models themselves (see town-pack.ts).
 */

export type Group = 'road' | 'nature' | 'decor' | 'small_house' | 'medium_house' | 'public' | 'large';

/** [id, group, price, unlock_at, English, Indonesian] */
export type Row = [string, Group, number, number, string, string];

export const SHOP: Row[] = [
  // roads
  ['road_straight', 'road', 5, 0, 'Road', 'Jalan'],
  ['road_corner', 'road', 5, 0, 'Road corner', 'Tikungan'],
  ['road_t', 'road', 5, 0, 'T junction', 'Pertigaan'],
  ['road_cross', 'road', 5, 0, 'Crossroads', 'Perempatan'],
  ['road_end', 'road', 5, 0, 'Dead end', 'Jalan buntu'],
  ['path_straight', 'road', 3, 0, 'Footpath', 'Jalan setapak'],
  ['path_corner', 'road', 3, 0, 'Footpath corner', 'Tikungan setapak'],
  ['path_t', 'road', 3, 0, 'Footpath T', 'Pertigaan setapak'],
  ['path_cross', 'road', 3, 0, 'Footpath cross', 'Perempatan setapak'],
  ['road_dirt_straight', 'road', 3, 0, 'Dirt road', 'Jalan tanah'],
  ['road_dirt_corner', 'road', 3, 0, 'Dirt road corner', 'Tikungan jalan tanah'],
  ['road_crosswalk', 'road', 6, 2, 'Zebra crossing', 'Zebra cross'],
  ['bridge_road', 'road', 15, 2, 'Bridge', 'Jembatan'],
  ['parking_lot', 'road', 10, 4, 'Car park', 'Parkiran'],
  ['road_roundabout', 'road', 10, 6, 'Roundabout', 'Bundaran'],
  ['avenue_straight', 'road', 8, 9, 'Avenue', 'Jalan raya'],
  ['avenue_corner', 'road', 8, 9, 'Avenue corner', 'Tikungan jalan raya'],
  ['avenue_t', 'road', 8, 9, 'Avenue T', 'Pertigaan jalan raya'],
  ['avenue_cross', 'road', 8, 9, 'Avenue cross', 'Perempatan jalan raya'],
  ['rail_straight', 'road', 10, 12, 'Railway', 'Rel kereta'],
  ['rail_corner', 'road', 10, 12, 'Railway corner', 'Tikungan rel'],
  ['rail_crossing', 'road', 12, 12, 'Level crossing', 'Perlintasan kereta'],
  ['highway_straight', 'road', 12, 20, 'Flyover', 'Jalan layang'],
  ['highway_corner', 'road', 12, 20, 'Flyover corner', 'Tikungan jalan layang'],
  ['highway_ramp', 'road', 12, 20, 'Flyover ramp', 'Tanjakan jalan layang'],
  ['highway_over_road', 'road', 15, 20, 'Flyover over a road', 'Jalan layang di atas jalan'],

  // trees and plants
  ['tree_round', 'nature', 10, 0, 'Round tree', 'Pohon bulat'],
  ['tree_pine', 'nature', 10, 0, 'Pine tree', 'Pohon pinus'],
  ['plant_bush', 'nature', 5, 0, 'Bush', 'Semak'],
  ['plant_flower_bush', 'nature', 6, 0, 'Flowering bush', 'Semak berbunga'],
  ['tree_palm', 'nature', 12, 2, 'Palm tree', 'Pohon palem'],
  ['tree_coconut', 'nature', 12, 2, 'Coconut tree', 'Pohon kelapa'],
  ['plant_hedge', 'nature', 5, 2, 'Hedge', 'Pagar tanaman'],
  ['plant_flower_pot', 'nature', 5, 2, 'Flower pot', 'Pot bunga'],
  ['plant_flower_bed', 'nature', 8, 2, 'Flower bed', 'Bedeng bunga'],
  ['tree_cypress', 'nature', 10, 4, 'Cypress', 'Pohon cemara'],
  ['tree_acacia', 'nature', 12, 4, 'Acacia', 'Pohon akasia'],
  ['plant_cactus', 'nature', 8, 4, 'Cactus', 'Kaktus'],
  ['plant_bamboo', 'nature', 10, 6, 'Bamboo', 'Bambu'],
  ['tree_sakura', 'nature', 15, 6, 'Cherry tree', 'Pohon sakura'],
  ['tree_banyan', 'nature', 20, 9, 'Banyan tree', 'Pohon beringin'],

  // nature tiles
  ['nature_grass', 'nature', 3, 0, 'Grass', 'Rumput'],
  ['nature_forest', 'nature', 15, 2, 'Little forest', 'Hutan kecil'],
  ['nature_rice_field', 'nature', 12, 4, 'Rice field', 'Sawah'],
  ['nature_hill', 'nature', 12, 6, 'Hill', 'Bukit'],
  ['nature_river_straight', 'nature', 10, 6, 'Stream', 'Sungai'],
  ['nature_river_corner', 'nature', 10, 6, 'Stream bend', 'Kelokan sungai'],
  ['nature_beach', 'nature', 12, 9, 'Beach', 'Pantai'],

  // street things
  ['prop_bench', 'nature', 10, 2, 'Bench', 'Bangku'],
  ['prop_street_lamp', 'nature', 15, 2, 'Street lamp', 'Lampu jalan'],
  ['prop_trash_bins', 'nature', 6, 2, 'Bins', 'Tempat sampah'],
  ['prop_fence', 'nature', 5, 2, 'Fence', 'Pagar'],
  ['prop_mailbox', 'nature', 6, 2, 'Postbox', 'Kotak pos'],
  ['prop_fountain', 'nature', 20, 4, 'Fountain', 'Air mancur'],
  ['prop_bus_stop', 'nature', 15, 4, 'Bus stop', 'Halte'],
  ['prop_traffic_light', 'nature', 12, 4, 'Traffic light', 'Lampu lalu lintas'],
  ['prop_stop_sign', 'nature', 6, 4, 'Stop sign', 'Rambu stop'],
  ['prop_warning_sign', 'nature', 6, 4, 'Warning sign', 'Rambu peringatan'],
  ['prop_direction_sign', 'nature', 8, 4, 'Signpost', 'Papan penunjuk arah'],
  ['prop_hydrant', 'nature', 6, 4, 'Fire hydrant', 'Hidran'],
  ['prop_cafe_table', 'nature', 10, 6, 'Cafe table', 'Meja kafe'],
  ['prop_beach_umbrella', 'nature', 10, 6, 'Beach umbrella', 'Payung pantai'],
  ['prop_phone_booth', 'nature', 10, 6, 'Phone box', 'Telepon umum'],
  ['prop_vending_machine', 'nature', 10, 6, 'Vending machine', 'Mesin minuman'],
  ['prop_flagpole', 'nature', 15, 9, 'Flagpole', 'Tiang bendera'],
  ['prop_statue', 'nature', 25, 9, 'Statue', 'Patung'],
  ['billboard_standing', 'nature', 6, 4, 'Sandwich board', 'Papan berdiri'],
  ['billboard_pole', 'nature', 15, 9, 'Billboard', 'Papan reklame'],
  ['billboard_wide', 'nature', 15, 9, 'Wide billboard', 'Baliho lebar'],
  ['billboard_rooftop', 'nature', 15, 12, 'Rooftop sign', 'Papan atap'],
  ['billboard_digital', 'nature', 20, 16, 'Digital screen', 'Papan digital'],

  // people, vehicles and animals: they may stand on a road
  ['people_man', 'decor', 5, 0, 'Man', 'Pria'],
  ['people_woman', 'decor', 5, 0, 'Woman', 'Wanita'],
  ['people_child', 'decor', 5, 0, 'Child with a balloon', 'Anak dengan balon'],
  ['people_student', 'decor', 5, 0, 'Student', 'Pelajar'],
  ['people_hijab', 'decor', 5, 2, 'Woman in a hijab', 'Wanita berhijab'],
  ['people_elderly', 'decor', 5, 2, 'Grandparent', 'Lansia'],
  ['people_jogger', 'decor', 5, 2, 'Jogger', 'Pelari'],
  ['people_sitting', 'decor', 5, 2, 'Sitting person', 'Orang duduk'],
  ['people_umbrella', 'decor', 5, 2, 'Person with an umbrella', 'Orang berpayung'],
  ['people_office_worker', 'decor', 6, 4, 'Office worker', 'Pekerja kantor'],
  ['people_cyclist', 'decor', 6, 4, 'Cyclist', 'Pesepeda'],
  ['people_vendor', 'decor', 8, 4, 'Street vendor', 'Pedagang gerobak'],
  ['people_police', 'decor', 6, 6, 'Police officer', 'Polisi'],
  ['people_doctor', 'decor', 6, 6, 'Doctor', 'Dokter'],
  ['people_worker', 'decor', 6, 6, 'Builder', 'Pekerja proyek'],
  ['vehicle_bicycle', 'decor', 5, 0, 'Bicycle', 'Sepeda'],
  ['vehicle_sedan', 'decor', 10, 2, 'Car', 'Mobil sedan'],
  ['vehicle_hatchback', 'decor', 10, 2, 'Small car', 'Mobil kecil'],
  ['vehicle_motorcycle', 'decor', 8, 2, 'Motorbike', 'Motor'],
  ['vehicle_becak', 'decor', 8, 2, 'Becak', 'Becak'],
  ['vehicle_bajaj', 'decor', 8, 4, 'Bajaj', 'Bajaj'],
  ['vehicle_taxi', 'decor', 10, 4, 'Taxi', 'Taksi'],
  ['vehicle_suv', 'decor', 12, 4, 'SUV', 'Mobil SUV'],
  ['vehicle_pickup', 'decor', 12, 4, 'Pickup truck', 'Mobil pikap'],
  ['vehicle_van', 'decor', 12, 6, 'Van', 'Mobil van'],
  ['vehicle_bus', 'decor', 15, 6, 'Bus', 'Bus kota'],
  ['vehicle_school_bus', 'decor', 15, 6, 'School bus', 'Bus sekolah'],
  ['vehicle_police', 'decor', 15, 9, 'Police car', 'Mobil polisi'],
  ['vehicle_ambulance', 'decor', 15, 9, 'Ambulance', 'Ambulans'],
  ['vehicle_fire_truck', 'decor', 15, 9, 'Fire engine', 'Mobil pemadam'],
  ['vehicle_truck', 'decor', 15, 9, 'Lorry', 'Truk'],
  ['vehicle_train_locomotive', 'decor', 20, 12, 'Train engine', 'Lokomotif'],
  ['vehicle_train_carriage', 'decor', 15, 12, 'Train carriage', 'Gerbong kereta'],
  ['animal_cat', 'decor', 5, 0, 'Cat', 'Kucing'],
  ['animal_bird', 'decor', 5, 0, 'Bird', 'Burung'],
  ['animal_cow', 'decor', 8, 2, 'Cow', 'Sapi'],
  ['animal_monkey', 'decor', 8, 4, 'Monkey', 'Monyet'],
  ['animal_penguin', 'decor', 8, 4, 'Penguin', 'Penguin'],
  ['animal_zebra', 'decor', 10, 6, 'Zebra', 'Zebra'],
  ['animal_giraffe', 'decor', 12, 6, 'Giraffe', 'Jerapah'],
  ['animal_lioness', 'decor', 12, 6, 'Lioness', 'Singa betina'],
  ['animal_lion', 'decor', 12, 9, 'Lion', 'Singa'],
  ['animal_elephant', 'decor', 15, 9, 'Elephant', 'Gajah'],

  // homes
  ['house_hut', 'small_house', 20, 0, 'Hut', 'Gubuk'],
  ['house_cottage', 'small_house', 30, 0, 'Cottage', 'Rumah mungil'],
  ['house_basic', 'small_house', 40, 0, 'House', 'Rumah'],
  ['house_stilt', 'small_house', 30, 2, 'Stilt house', 'Rumah panggung'],
  ['house_minimalist', 'small_house', 40, 2, 'Flat roof house', 'Rumah minimalis'],
  ['house_row', 'small_house', 45, 2, 'Terraced houses', 'Rumah deret'],
  ['house_garage', 'small_house', 50, 4, 'House with a garage', 'Rumah bergarasi'],
  ['house_two_storey', 'medium_house', 60, 4, 'Two storey house', 'Rumah dua lantai'],
  ['house_bungalow', 'medium_house', 60, 4, 'Bungalow', 'Bungalow'],
  ['house_garden', 'medium_house', 65, 6, 'House with a garden', 'Rumah berkebun'],
  ['house_joglo', 'medium_house', 70, 6, 'Joglo house', 'Rumah joglo'],
  ['house_gadang', 'medium_house', 75, 6, 'Gadang house', 'Rumah gadang'],
  ['house_colonial', 'medium_house', 80, 9, 'Colonial house', 'Rumah kolonial'],
  ['house_modern_glass', 'medium_house', 85, 9, 'Glass house', 'Rumah kaca modern'],
  ['house_duplex', 'medium_house', 90, 9, 'Semi-detached houses', 'Rumah kopel'],
  ['house_apartment', 'medium_house', 110, 12, 'Small block of flats', 'Apartemen kecil'],
  ['house_villa_pool', 'medium_house', 140, 16, 'Villa with a pool', 'Villa berkolam'],
  ['house_flats', 'medium_house', 160, 16, 'Tower of flats', 'Rumah susun'],
  ['house_luxury', 'medium_house', 200, 20, 'Modern mansion', 'Rumah mewah'],
  ['house_mansion', 'medium_house', 260, 25, 'Palace', 'Istana'],

  // parks, sports and the zoo
  ['park_flower', 'medium_house', 40, 2, 'Flower garden', 'Taman bunga'],
  ['park_picnic', 'medium_house', 40, 2, 'Picnic park', 'Taman piknik'],
  ['park_playground', 'medium_house', 45, 4, 'Playground', 'Taman bermain'],
  ['park_pond', 'medium_house', 45, 4, 'Pond', 'Taman kolam'],
  ['park_fountain', 'medium_house', 50, 4, 'Fountain park', 'Taman air mancur'],
  ['park_community_garden', 'medium_house', 50, 6, 'Community garden', 'Kebun warga'],
  ['park_zen', 'medium_house', 55, 6, 'Rock garden', 'Taman batu'],
  ['park_statue', 'medium_house', 60, 9, 'Statue park', 'Taman patung'],
  ['park_square', 'public', 150, 16, 'Town square', 'Alun-alun'],
  ['sport_basketball', 'public', 70, 6, 'Basketball court', 'Lapangan basket'],
  ['sport_badminton', 'public', 70, 6, 'Badminton court', 'Lapangan bulu tangkis'],
  ['sport_tennis', 'public', 75, 9, 'Tennis court', 'Lapangan tenis'],
  ['sport_skatepark', 'public', 75, 9, 'Skatepark', 'Skatepark'],
  ['sport_pool', 'public', 90, 12, 'Swimming pool', 'Kolam renang'],
  ['sport_soccer', 'public', 120, 12, 'Football pitch', 'Lapangan sepak bola'],
  ['sport_stadium', 'large', 350, 30, 'Stadium', 'Stadion'],
  ['zoo_gate', 'public', 60, 12, 'Zoo gate', 'Gerbang kebun binatang'],
  ['zoo_penguin', 'public', 80, 12, 'Penguin pool', 'Kolam penguin'],
  ['zoo_monkey', 'public', 80, 12, 'Monkey island', 'Pulau monyet'],
  ['zoo_aviary', 'public', 85, 16, 'Aviary', 'Kandang burung'],
  ['zoo_giraffe', 'public', 90, 16, 'Giraffe pen', 'Kandang jerapah'],
  ['zoo_lion', 'public', 95, 16, 'Lion den', 'Kandang singa'],
  ['zoo_elephant', 'public', 100, 20, 'Elephant pen', 'Kandang gajah'],

  // shops and work
  ['shop_general', 'public', 60, 2, 'Corner shop', 'Toko'],
  ['office_shophouse', 'public', 90, 4, 'Shophouse', 'Ruko'],
  ['shop_cafe', 'public', 70, 4, 'Cafe', 'Kafe'],
  ['shop_minimarket', 'public', 75, 6, 'Minimarket', 'Minimarket'],
  ['shop_restaurant', 'public', 80, 6, 'Restaurant', 'Restoran'],
  ['shop_gas_station', 'public', 90, 9, 'Petrol station', 'SPBU'],
  ['shop_bank', 'public', 100, 9, 'Bank', 'Bank'],
  ['shop_cinema', 'public', 110, 12, 'Cinema', 'Bioskop'],
  ['shop_market', 'public', 130, 12, 'Market', 'Pasar'],
  ['shop_hotel', 'large', 180, 20, 'Hotel', 'Hotel'],
  ['shop_mall', 'large', 300, 30, 'Shopping mall', 'Mal'],
  ['office_small', 'public', 80, 6, 'Small office', 'Kantor kecil'],
  ['office_creative', 'public', 100, 9, 'Creative studio', 'Kantor kreatif'],
  ['office_campus', 'public', 140, 16, 'Business park', 'Kampus bisnis'],
  ['office_glass_tower', 'large', 250, 20, 'Office tower', 'Menara kantor'],
  ['office_stepped', 'large', 260, 20, 'Stepped tower', 'Menara bertingkat'],
  ['office_round', 'large', 270, 25, 'Round tower', 'Menara silinder'],
  ['office_helipad', 'large', 280, 25, 'Tower with a helipad', 'Menara helipad'],
  ['office_twin', 'large', 380, 30, 'Twin towers', 'Menara kembar'],
  ['office_spire', 'large', 420, 36, 'Skyscraper', 'Pencakar langit'],
  ['industry_silo', 'public', 80, 9, 'Silo', 'Silo'],
  ['industry_warehouse', 'public', 120, 12, 'Warehouse', 'Gudang'],
  ['industry_factory', 'large', 250, 20, 'Factory', 'Pabrik'],

  // public buildings
  ['public_kindergarten', 'public', 90, 2, 'Kindergarten', 'TK'],
  ['public_school', 'public', 120, 4, 'School', 'Sekolah'],
  ['public_clinic', 'public', 100, 6, 'Health centre', 'Puskesmas'],
  ['public_post_office', 'public', 100, 6, 'Post office', 'Kantor pos'],
  ['public_library', 'public', 110, 6, 'Library', 'Perpustakaan'],
  ['public_mosque', 'public', 120, 6, 'Mosque', 'Masjid'],
  ['public_church', 'public', 120, 6, 'Church', 'Gereja'],
  ['public_temple', 'public', 120, 6, 'Temple', 'Pura'],
  ['public_police', 'public', 120, 9, 'Police station', 'Kantor polisi'],
  ['public_fire_station', 'public', 120, 9, 'Fire station', 'Pemadam kebakaran'],
  ['public_water_tower', 'public', 90, 9, 'Water tower', 'Menara air'],
  ['public_bus_terminal', 'public', 150, 12, 'Bus station', 'Terminal bus'],
  ['public_museum', 'public', 180, 16, 'Museum', 'Museum'],
  ['public_train_station', 'public', 180, 16, 'Train station', 'Stasiun kereta'],
  ['public_hospital', 'large', 220, 20, 'Hospital', 'Rumah sakit'],
  ['public_city_hall', 'large', 240, 20, 'Town hall', 'Balai kota'],
  ['public_university', 'large', 320, 25, 'University', 'Universitas'],
  ['public_power_plant', 'large', 300, 25, 'Power station', 'Pembangkit listrik'],
  ['public_airport', 'large', 400, 36, 'Airport', 'Bandara'],
];

/** Shelves of the shop, in order, with the sheets of the asset set they hold. */
export const SHELVES: [shelf: string, sheets: string[], en: string, id: string][] = [
  ['roads', ['roads'], 'ROADS', 'JALAN'],
  ['homes', ['houses'], 'HOMES', 'RUMAH'],
  ['nature', ['plants', 'nature'], 'NATURE', 'ALAM'],
  ['parks', ['parks', 'sports', 'zoo'], 'PARKS', 'TAMAN'],
  ['shops', ['commercial', 'offices', 'industry'], 'SHOPS & WORK', 'TOKO & KERJA'],
  ['public', ['public'], 'PUBLIC', 'UMUM'],
  ['street', ['props', 'billboards'], 'STREET', 'PERABOT'],
  ['life', ['people', 'vehicles', 'animals'], 'PEOPLE & CARS', 'ORANG & MOBIL'],
];

/** Ids the town once used, still read in old events. */
export const ALIASES: [old: string, now: string][] = [
  ['bench', 'prop_bench'],
  ['lamp', 'prop_street_lamp'],
  ['fountain', 'prop_fountain'],
  ['shophouse', 'office_shophouse'],
  ['school', 'public_school'],
  ['office_tower', 'office_glass_tower'],
  ['stadium', 'sport_stadium'],
];

/** The skill landmarks, by the id the core gives, with the model of each tier. */
export const LANDMARKS: [landmark: string, model: string, en: string, id: string][] = [
  ['landmark_fraction_bridge', 'skill_fraction_bridge', 'Fraction Bridge', 'Jembatan Pecahan'],
  ['landmark_times_tower', 'skill_multiply_tower', 'Times Tower', 'Menara Perkalian'],
  ['landmark_number_hall', 'skill_placevalue_hall', 'Number Hall', 'Balai Angka'],
  ['landmark_decimal_market', 'skill_decimal_market', 'Decimal Market', 'Pasar Desimal'],
  ['landmark_clock_tower', 'skill_measure_clocktower', 'Clock Tower', 'Menara Jam'],
];

/** Floors the models' windows do not show, set by hand. */
export const FLOORS: Record<string, number> = {
  office_shophouse: 3,
  house_mansion: 2,
  shop_mall: 2,
  public_church: 1,
  public_city_hall: 2,
};
