import type { Lang } from '../settings.js';
import type { Shape } from './measure-core.js';

/** Words of Measure Hunt, in English and Indonesian. */

const EN = {
  title: 'MEASURE HUNT',
  xrOnly: 'XR ONLY',
  needHeadset: 'Measure Hunt needs the headset: it measures your real desk with your hands.',
  pickGrade: 'WHICH GRADE?',
  grade: (g: number) => `GRADE ${g}`,
  pickGroup: 'WHAT WILL YOU MEASURE?',
  flat: 'FLAT SHAPES',
  solid: 'SOLIDS',
  pickSource: 'WHICH OBJECT?',
  paper: 'PAPER OBJECT',
  real: 'SOMETHING NEAR YOU',
  realNote: 'Find something real: a book, a box, a table top, a cup.',
  start: 'START',
  back: 'BACK',
  howTitle: 'HOW TO MEASURE',
  how: [
    'Point your index finger at a corner and hold still: a pin drops.',
    'Pinch a pin and pull a thread to the next corner.',
    'Throw a pin off the desk to take it away.',
  ],
  howController: 'With controllers: point at a corner and press the trigger for a pin; hold it on a pin to pull a thread. A, B, X or Y turns a solid a quarter.',
  howSolid: 'Grab the paper solid to turn it, flick it to spin. Pull it apart with both hands to unfold its net.',
  clear: 'CLEAR',
  skip: 'SKIP',
  quit: 'QUIT',
  again: 'AGAIN',
  done: 'DONE',
  pi: 'π = 3.14',
  time: (s: number) => `${Math.floor(s / 60)}:${String(Math.floor(s % 60)).padStart(2, '0')}`,
  noTimer: 'NO TIMER',
  steps: {
    square: 'Pin the 4 corners, then thread them round.',
    rectangle: 'Pin the 4 corners, then thread them round.',
    triangle: 'Pin the 3 corners, then thread them round.',
    triangleArea: 'Thread the 3 sides, then pull a thread from a corner straight down to the opposite side.',
    circle: 'Pin the centre, then pull a thread to the edge.',
    cylinder: 'Pin the centre of the top, then pull a thread to its edge.',
    sphere: 'Pin one side of the ball, then thread straight across to the other side.',
    box: 'Place 4 pins: one corner and the 3 corners right next to it. Then pull a thread from that corner to each of the other 3 pins.',
  } as Record<Exclude<Shape, 'cube' | 'cuboid'> | 'triangleArea' | 'box', string>,
  problem: {
    need_pins: 'Not all the pins and threads are there yet.',
    off_corner: 'A pin is not on a corner.',
    same_corner: 'Two pins are on the same corner.',
    diagonal: 'A thread goes across, not along a side.',
    not_an_edge: 'A thread does not go along an edge.',
    off_centre: 'The first pin is not at the centre.',
    off_rim: 'The thread does not end on the edge.',
    not_across: 'The thread does not go straight across the ball.',
    height_not_upright: 'The height must stand straight up on the side.',
    too_small: 'Too small to measure with a finger: find something bigger.',
    not_square_corner: 'The corners are not square: this is not the shape asked for.',
    sides_differ: 'Opposite sides are not the same length.',
    not_square: 'The sides are not all the same: this is not a square.',
    not_cube: 'The edges are not all the same: this is not a cube.',
    not_flat: 'The pins are not all on one flat face.',
    flat_triangle: 'The three pins are almost in a line.',
  } as Record<string, string>,
  allPins: (n: number) => `All ${n} pins are placed: throw one off the desk, or CLEAR.`,
  oneCorner: 'All 3 threads must start from the same corner pin.',
  measured: (n: number) => `Measured well: +${n}`,
  right: (n: number) => `Right! +${n}`,
  wrongWas: (answer: string) => `It was ${answer}`,
  recap: 'TIME!',
  recapLine: (right: number, answered: number, points: number) => `${right} of ${answered} right · ${points} points`,
  unit: { cm: 'cm', cm2: 'cm²', cm3: 'cm³' } as Record<string, string>,
  failed: 'Measure Hunt could not start here. Try again.',
};

type MeasureText = typeof EN;

const ID: MeasureText = {
  title: 'BURU UKUR',
  xrOnly: 'KHUSUS XR',
  needHeadset: 'Buru Ukur butuh headset: kamu mengukur meja nyata dengan tanganmu.',
  pickGrade: 'KELAS BERAPA?',
  grade: (g: number) => `KELAS ${g}`,
  pickGroup: 'APA YANG AKAN DIUKUR?',
  flat: 'BANGUN DATAR',
  solid: 'BANGUN RUANG',
  pickSource: 'BENDA APA?',
  paper: 'BENDA KERTAS',
  real: 'BENDA DI SEKITARMU',
  realNote: 'Cari benda nyata: buku, kotak, permukaan meja, gelas.',
  start: 'MULAI',
  back: 'KEMBALI',
  howTitle: 'CARA MENGUKUR',
  how: [
    'Tunjuk sudut dengan telunjuk lalu tahan diam: pin jatuh.',
    'Cubit pin lalu tarik benang ke sudut berikutnya.',
    'Lempar pin keluar meja untuk membuangnya.',
  ],
  howController: 'Dengan controller: tunjuk sudut lalu tekan trigger untuk memasang pin; tahan pada pin untuk menarik benang. A, B, X atau Y memutar bangun ruang seperempat putaran.',
  howSolid: 'Pegang bangun kertas untuk memutarnya, jentik untuk memutar cepat. Tarik dengan dua tangan untuk membuka jaring-jaringnya.',
  clear: 'HAPUS',
  skip: 'LEWATI',
  quit: 'KELUAR',
  again: 'LAGI',
  done: 'SELESAI',
  pi: 'π = 3,14',
  time: EN.time,
  noTimer: 'TANPA WAKTU',
  steps: {
    square: 'Pasang pin di 4 sudut, lalu sambung dengan benang berkeliling.',
    rectangle: 'Pasang pin di 4 sudut, lalu sambung dengan benang berkeliling.',
    triangle: 'Pasang pin di 3 sudut, lalu sambung dengan benang berkeliling.',
    triangleArea: 'Sambung 3 sisinya, lalu tarik benang dari satu sudut tegak lurus ke sisi di depannya.',
    circle: 'Pasang pin di pusat, lalu tarik benang ke tepi.',
    cylinder: 'Pasang pin di pusat tutup atas, lalu tarik benang ke tepinya.',
    sphere: 'Pasang pin di satu sisi bola, lalu tarik benang lurus ke sisi seberang.',
    box: 'Pasang 4 pin: satu sudut dan 3 sudut yang bersebelahan dengannya. Lalu tarik benang dari pin sudut itu ke ketiga pin lainnya.',
  },
  problem: {
    need_pins: 'Pin dan benangnya belum lengkap.',
    off_corner: 'Ada pin yang tidak di sudut.',
    same_corner: 'Dua pin ada di sudut yang sama.',
    diagonal: 'Ada benang yang menyilang, bukan di sisi.',
    not_an_edge: 'Ada benang yang tidak di rusuk.',
    off_centre: 'Pin pertama tidak di pusat.',
    off_rim: 'Benang tidak berakhir di tepi.',
    not_across: 'Benang tidak lurus melintasi bola.',
    height_not_upright: 'Tinggi harus tegak lurus pada sisinya.',
    too_small: 'Terlalu kecil untuk diukur dengan jari: cari yang lebih besar.',
    not_square_corner: 'Sudutnya tidak siku: ini bukan bangun yang diminta.',
    sides_differ: 'Sisi yang berhadapan tidak sama panjang.',
    not_square: 'Sisinya tidak sama semua: ini bukan persegi.',
    not_cube: 'Rusuknya tidak sama semua: ini bukan kubus.',
    not_flat: 'Pinnya tidak berada di satu bidang datar.',
    flat_triangle: 'Ketiga pin hampir segaris.',
  },
  allPins: (n: number) => `Semua ${n} pin sudah terpasang: lempar satu keluar meja, atau HAPUS.`,
  oneCorner: 'Ketiga benang harus berawal dari pin sudut yang sama.',
  measured: (n: number) => `Pengukuran bagus: +${n}`,
  right: (n: number) => `Benar! +${n}`,
  wrongWas: (answer: string) => `Jawabannya ${answer}`,
  recap: 'WAKTU HABIS!',
  recapLine: (right: number, answered: number, points: number) => `${right} dari ${answered} benar · ${points} poin`,
  unit: EN.unit,
  failed: 'Buru Ukur tidak bisa dimulai di sini. Coba lagi.',
};

export const MEASURE_TEXT: Record<Lang, MeasureText> = { en: EN, id: ID };
