import type { Lang } from '../settings.js';
import type { Shape } from './measure-core.js';

/** Words of Measure Hunt, in English and Indonesian. */

const EN = {
  title: 'MEASURE HUNT',
  xrOnly: 'XR ONLY',
  featured: 'Measure real things with your hands',
  badge: 'NEW',
  badgeXr: 'XR',
  needHeadset: 'Measure Hunt needs the headset: it measures your real desk with your hands.',
  infoHint: 'Put on your headset and open the game from there.',
  pickGrade: 'WHICH GRADE?',
  grade: (g: number) => `GRADE ${g}`,
  pickGroup: 'WHAT WILL YOU MEASURE?',
  flat: 'FLAT SHAPES',
  solid: 'SOLIDS',
  pickSource: 'WHICH OBJECT?',
  paper: 'PAPER OBJECT',
  real: 'SOMETHING NEAR YOU',
  realNote: 'Find something real near you that is flat or a box.',
  pickObject: 'WHAT DO YOU HAVE?',
  objectNote: 'A book is a rectangle, a plate a circle, a box a box. It must be bigger than 5 cm.',
  realTask: 'Pin the corners of your object. A box is pinned along its base, then up from a corner.',
  shapes: {
    square: 'SQUARE',
    rectangle: 'RECTANGLE',
    triangle: 'TRIANGLE',
    circle: 'CIRCLE',
    cube: 'CUBE',
    cuboid: 'BOX',
  } as Record<string, string>,
  start: 'START',
  back: 'BACK',
  howTitle: 'HOW TO MEASURE',
  how: [
    'Point your index finger at a corner and hold still: a pin drops.',
    'Pinch a pin and pull a thread to the next corner.',
    'Throw a pin off the desk, or point at it and press the bin that appears, to take it away.',
  ],
  howHand: [
    'Point at a corner: a circle shows. Tap, and a line starts there and follows your hand.',
    'Point at the next corner and tap: the line is fixed, and the next one starts.',
    'When the lines are enough, the answers come. Tap a pin and then the bin beside it to take it away.',
  ],
  howTrigger: [
    'Point at a corner: a circle shows. Press the trigger, and a line starts there and follows your hand.',
    'Point at the next corner and press: the line is fixed, and the next one starts.',
    'When the lines are enough, the answers come. Press a pin and then the bin beside it to take it away.',
  ],
  howSolidHand: 'Turn the solid with the arrow cards at the left, to reach every corner; NET opens it flat.',
  howSolid: 'Grab the paper solid to turn it, flick it to spin. Pull it apart with both hands to unfold its net.',
  tapHand: 'Aim at a spot and tap your index finger: a pin drops. Aim at the next spot and tap: a thread joins them and shows its length.',
  tapTrigger: 'Aim at a spot and press the trigger: a pin drops. Aim at the next spot and press: a thread joins them and shows its length.',
  toolsNote: 'Arrows turn it. NET opens it. READ brings the board close.',
  sweepNote: 'Sweep a finger over it to turn it.',
  sweepBall: 'Sweep a finger over the ball to turn it.',
  zoom: 'READ',
  turnLeft: 'LEFT',
  turnRight: 'RIGHT',
  turnUp: 'UP',
  turnDown: 'DOWN',
  net: 'NET',
  turn: 'TURN',
  spinTurn: 'Sweep your hand over the ball to turn it.',
  onRing: 'Pin the ring round the middle.',
  findMiddle: 'Look through the ball: a mark shows at its middle.',
  spinClose: 'The line is back at its start. Tap that pin.',
  clear: 'CLEAR',
  skip: 'SKIP',
  quit: 'QUIT',
  again: 'AGAIN',
  done: 'DONE',
  pi: 'π = 3.14',
  time: (s: number) => `${Math.floor(s / 60)}:${String(Math.floor(s % 60)).padStart(2, '0')}`,
  noTimer: 'NO TIMER',
  steps: {
    square: 'Pin a corner and its two neighbours. Thread the two sides.',
    rectangle: 'Pin a corner and its two neighbours. Thread the two sides.',
    triangle: 'Pin the 3 corners. Thread them round.',
    triangleArea: 'Thread the 3 sides. Then pull a thread from a corner straight to the opposite side.',
    circle: 'Pin the middle. Pull a line to the edge.',
    cylinder: 'Pin the middle of the top. Pull a line to its rim.',
    cylinderVolume: 'Pin the middle of the top and a point on the rim. Then pull straight down to the desk.',
    sphere: 'Pin the middle of the ball. Pull a line to the ring. Then turn the ball.',
    sphereVolume: 'Pin the middle of the ball. Pull a line to the ring.',
    box: 'Pin a corner. Thread three edges at right angles: along, across, up.',
  } as Record<Exclude<Shape, 'cube' | 'cuboid'> | 'triangleArea' | 'box' | 'cylinderVolume' | 'sphereVolume', string>,
  problem: {
    need_pins: 'Not all the pins and threads are there yet.',
    off_corner: 'A pin is not on a corner.',
    same_corner: 'Two pins are on the same corner.',
    diagonal: 'A thread goes across, not along a side.',
    not_an_edge: 'A thread does not go along an edge.',
    off_centre: 'The first pin is not at the centre.',
    off_rim: 'The thread does not end on the edge.',
    not_across: 'The thread does not go straight across the ball.',
    height_not_upright: 'The height must stand straight up on the side.',
    too_small: 'Too small to measure with a finger: find something bigger.',
    not_square_corner: 'The corners are not square: this is not the shape asked for.',
    sides_differ: 'Opposite sides are not the same length.',
    not_square: 'The sides are not all the same: this is not a square.',
    not_cube: 'The edges are not all the same: this is not a cube.',
    not_flat: 'The pins are not all on one flat face.',
    flat_triangle: 'The three pins are almost in a line.',
  } as Record<string, string>,
  farPin: 'Pins go on the object, at its corners: this is too far from one.',
  allPins: (n: number) => `All ${n} pins are placed: throw one off the desk, or CLEAR.`,
  oneCorner: 'Thread three edges square to each other: along, across and up.',
  measured: (n: number) => `Measured well: +${n}`,
  right: (n: number) => `Right! +${n}`,
  wrongWas: (answer: string) => `It was ${answer}`,
  recap: 'TIME!',
  recapLine: (right: number, answered: number, points: number) => `${right} of ${answered} right · ${points} points`,
  unit: { cm: 'cm', cm2: 'cm²', cm3: 'cm³' } as Record<string, string>,
  failed: 'Measure Hunt could not start here. Try again.',
};

type MeasureText = typeof EN;

const ID: MeasureText = {
  title: 'CARI & UKUR',
  xrOnly: 'KHUSUS XR',
  featured: 'Ukur benda nyata dengan tanganmu',
  badge: 'BARU',
  badgeXr: 'XR',
  needHeadset: 'Cari & Ukur butuh headset: kamu mengukur meja nyata dengan tanganmu.',
  infoHint: 'Pakai headset-mu dan buka game dari sana.',
  pickGrade: 'KELAS BERAPA?',
  grade: (g: number) => `KELAS ${g}`,
  pickGroup: 'APA YANG AKAN DIUKUR?',
  flat: 'BANGUN DATAR',
  solid: 'BANGUN RUANG',
  pickSource: 'BENDA APA?',
  paper: 'BENDA KERTAS',
  real: 'BENDA DI SEKITARMU',
  realNote: 'Cari benda nyata di dekatmu yang datar atau berbentuk kotak.',
  pickObject: 'APA YANG KAMU PUNYA?',
  objectNote: 'Buku itu persegi panjang, piring itu lingkaran, kardus itu balok. Ukurannya harus lebih dari 5 cm.',
  realTask: 'Pasang pin di sudut bendamu. Balok dipasang di alasnya dulu, lalu ke atas dari satu sudut.',
  shapes: {
    square: 'PERSEGI',
    rectangle: 'PERSEGI PANJANG',
    triangle: 'SEGITIGA',
    circle: 'LINGKARAN',
    cube: 'KUBUS',
    cuboid: 'BALOK',
  },
  start: 'MULAI',
  back: 'KEMBALI',
  howTitle: 'CARA MENGUKUR',
  how: [
    'Tunjuk sudut dengan telunjuk lalu tahan diam: pin jatuh.',
    'Cubit pin lalu tarik benang ke sudut berikutnya.',
    'Lempar pin keluar meja, atau arahkan ke pin lalu tekan tempat sampah yang muncul, untuk membuangnya.',
  ],
  howHand: [
    'Tunjuk sebuah sudut: bulatan muncul. Tap, dan garis mulai dari sana mengikuti tanganmu.',
    'Tunjuk sudut berikutnya lalu tap: garis dipatenkan, dan garis berikutnya dimulai.',
    'Kalau garisnya cukup, pilihan jawaban muncul. Tap pin lalu tempat sampah di sampingnya untuk membuangnya.',
  ],
  howTrigger: [
    'Tunjuk sebuah sudut: bulatan muncul. Tekan trigger, dan garis mulai dari sana mengikuti tanganmu.',
    'Tunjuk sudut berikutnya lalu tekan: garis dipatenkan, dan garis berikutnya dimulai.',
    'Kalau garisnya cukup, pilihan jawaban muncul. Tekan pin lalu tempat sampah di sampingnya untuk membuangnya.',
  ],
  howSolidHand: 'Putar bangun dengan kartu panah di kiri untuk menjangkau semua sudut; JARING membukanya datar.',
  howSolid: 'Pegang bangun kertas untuk memutarnya, jentik untuk memutar cepat. Tarik dengan dua tangan untuk membuka jaring-jaringnya.',
  tapHand: 'Bidik satu titik lalu tap telunjuk: pin jatuh. Bidik titik berikutnya lalu tap: benang menyambung keduanya dan menunjukkan panjangnya.',
  tapTrigger: 'Bidik satu titik lalu tekan trigger: pin jatuh. Bidik titik berikutnya lalu tekan: benang menyambung keduanya dan menunjukkan panjangnya.',
  toolsNote: 'Panah memutar. JARING membuka. BACA mendekatkan papan.',
  sweepNote: 'Usap dengan jari untuk memutarnya.',
  sweepBall: 'Usap bola dengan jari untuk memutarnya.',
  zoom: 'BACA',
  turnLeft: 'KIRI',
  turnRight: 'KANAN',
  turnUp: 'ATAS',
  turnDown: 'BAWAH',
  net: 'JARING',
  turn: 'PUTAR',
  spinTurn: 'Usap bola dengan tanganmu untuk memutarnya.',
  onRing: 'Pasang pin di garis lingkar tengah.',
  findMiddle: 'Tembus kaca bola: tanda muncul di pusatnya.',
  spinClose: 'Garis kembali ke titik awal. Tap pin itu.',
  clear: 'HAPUS',
  skip: 'LEWATI',
  quit: 'KELUAR',
  again: 'LAGI',
  done: 'SELESAI',
  pi: 'π = 3,14',
  time: EN.time,
  noTimer: 'TANPA WAKTU',
  steps: {
    square: 'Pin satu sudut dan dua sudut tetangganya. Sambung kedua sisinya.',
    rectangle: 'Pin satu sudut dan dua sudut tetangganya. Sambung kedua sisinya.',
    triangle: 'Pin 3 sudut. Sambung berkeliling.',
    triangleArea: 'Sambung 3 sisi. Lalu tarik benang dari satu sudut tegak lurus ke sisi seberang.',
    circle: 'Pin di pusat. Tarik garis ke tepi.',
    cylinder: 'Pin pusat tutup. Tarik garis ke tepinya.',
    cylinderVolume: 'Pin pusat tutup dan satu titik tepi. Lalu tarik lurus ke bawah sampai meja.',
    sphere: 'Pin pusat bola. Tarik garis ke garis lingkar. Lalu putar bola.',
    sphereVolume: 'Pin pusat bola. Tarik garis ke garis lingkar.',
    box: 'Pin satu sudut. Sambung tiga rusuk siku-siku: panjang, lebar, tinggi.',
  },
  problem: {
    need_pins: 'Pin dan benangnya belum lengkap.',
    off_corner: 'Ada pin yang tidak di sudut.',
    same_corner: 'Dua pin ada di sudut yang sama.',
    diagonal: 'Ada benang yang menyilang, bukan di sisi.',
    not_an_edge: 'Ada benang yang tidak di rusuk.',
    off_centre: 'Pin pertama tidak di pusat.',
    off_rim: 'Benang tidak berakhir di tepi.',
    not_across: 'Benang tidak lurus melintasi bola.',
    height_not_upright: 'Tinggi harus tegak lurus pada sisinya.',
    too_small: 'Terlalu kecil untuk diukur dengan jari: cari yang lebih besar.',
    not_square_corner: 'Sudutnya tidak siku: ini bukan bangun yang diminta.',
    sides_differ: 'Sisi yang berhadapan tidak sama panjang.',
    not_square: 'Sisinya tidak sama semua: ini bukan persegi.',
    not_cube: 'Rusuknya tidak sama semua: ini bukan kubus.',
    not_flat: 'Pinnya tidak berada di satu bidang datar.',
    flat_triangle: 'Ketiga pin hampir segaris.',
  },
  farPin: 'Pin dipasang pada benda, di sudutnya: titik ini terlalu jauh dari sudut.',
  allPins: (n: number) => `Semua ${n} pin sudah terpasang: lempar satu keluar meja, atau HAPUS.`,
  oneCorner: 'Sambung tiga rusuk yang saling tegak lurus: memanjang, melebar dan ke atas.',
  measured: (n: number) => `Pengukuran bagus: +${n}`,
  right: (n: number) => `Benar! +${n}`,
  wrongWas: (answer: string) => `Jawabannya ${answer}`,
  recap: 'WAKTU HABIS!',
  recapLine: (right: number, answered: number, points: number) => `${right} dari ${answered} benar · ${points} poin`,
  unit: EN.unit,
  failed: 'Cari & Ukur tidak bisa dimulai di sini. Coba lagi.',
};

export const MEASURE_TEXT: Record<Lang, MeasureText> = { en: EN, id: ID };
