import type { Lang } from '../settings.js';
import type { LandKind } from './town-core.js';
import { NAMES_EN, NAMES_ID } from './town-names.js';

/** Words of MY FOLD TOWN, in English and Indonesian. */

const EN = {
  title: 'MY FOLD TOWN',
  folds: (n: number) => `${n} FOLDS`,
  close: 'CLOSE',
  land: (n: number) => `LAND ${n}`,
  newLand: 'NEW LAND',
  how: 'HOW FOLDS WORK',
  sampleOpen: 'SEE A SAMPLE TOWN',
  sampleTitle: 'SAMPLE FOLD TOWN',
  buildMine: 'BUILD MY OWN',
  sampleNote:
    'A sample town to look at only: how a town can grow over weeks of play, with a landmark on each land. Pick a building to see its maths, or a landmark to see the skill that raised it.',
  sampleKeys: 'Arrows move · Enter picks · Esc closes',
  loading: 'Opening your town...',
  failed: 'The town could not be opened here. Try again.',
  shop: 'SHOP',
  price: (n: number) => `${n} Folds`,
  lockedAfter: (n: number) => `After ${n} buildings`,
  needFolds: (n: number) => `${n} more Folds`,
  keys: 'Arrows move · R turns · Enter places · Delete removes · Esc stops',
  pickLand: 'PICK YOUR LAND',
  pickLandNote: 'Each land is one page of your book. Its river, hills or beach stay as they are, and the gold star keeps a place for a landmark you earn by learning.',
  kinds: {
    plain: ['PLAIN', 'Open grass, every tile free to build on.'],
    river: ['RIVER', 'A river runs across the middle. Your fractions landmark can bridge it.'],
    hills: ['HILLS', 'Green hills rise in one corner.'],
    beach: ['BEACH', 'A sandy shore along the front.'],
  } as Record<LandKind, [string, string]>,
  pickCell: 'PICK YOUR PLACE ON THE CLASS MAP',
  pickCellNote: 'Your land joins your class map here. Your classmates see your player name, your teacher sees your seat number. Pick an empty square.',
  pickCellLater: 'You are offline. Build now; pick your place on the class map next time you are online.',
  cellTaken: 'Someone took that square just now. Pick another.',
  you: 'YOU',
  later: 'LATER',
  back: 'BACK',
  status: {
    building: (t: string) => `Being built: ready in ${t}`,
    ready: 'Finished',
  },
  move: 'MOVE',
  remove: 'REMOVE',
  refund: (n: number) => `REMOVE (+${n} FOLDS BACK)`,
  turn: 'TURN',
  cancel: 'CANCEL',
  placed: (name: string) => `${name} placed.`,
  removed: (name: string, n: number) => `${name} removed, ${n} Folds back.`,
  moved: (name: string) => `${name} moved.`,
  finished: (name: string) => `${name} is finished!`,
  tile: (x: number, y: number) => `Tile ${x + 1}, ${y + 1}`,
  empty: 'empty',
  landClosed: (used: number, need: number) => `Build on ${need} tiles of this land to open a new one (${used} so far).`,
  refusedTitle: 'NOT KEPT',
  refusedNote: 'These changes could not be kept by the server, so your town is as the server has it:',
  ok: 'OK',
  offline: 'Offline: your changes wait on this device and go when you are back online.',
  howBody: [
    'Every play gives Folds: one for every 10 points, and 10 more for finishing.',
    'Playing on days in a row adds a streak bonus, up to 25 Folds a day.',
    'Practice and robot races give up to 100 Folds a day; class races, rooms and FIND A RIVAL have no limit.',
    'A new building stands as a paper frame for a few minutes before it is finished. Removing a building gives back every Fold it cost.',
    'CITY BUILDER on the leaderboard counts the Folds in your finished buildings.',
  ],
  earned: (e: { plays: number; streak: number; welcome: number; held_back: number }) =>
    `Earned: ${e.plays} from plays, ${e.streak} from streaks, ${e.welcome} welcome gift${e.held_back ? `. ${e.held_back} held back by the daily limit.` : '.'}`,
  reasons: {
    not_enough_folds: 'Not enough Folds yet. Play a game to earn more.',
    look_only: 'The sample town is to look at only. Build your own with BUILD MY OWN.',
    taken: 'Something already stands there.',
    nature: 'You cannot build on water, hills or sand.',
    landmark_plot: 'The gold star keeps these two tiles for a landmark.',
    needs_water: 'A bridge goes over water.',
    off_land: 'It does not fit on the page there.',
    locked: 'The shop opens this after more buildings.',
    land_not_full: 'Build more on this land first.',
    too_many_lands: 'Your book has no more pages.',
    unknown_place: 'That building is no longer there.',
    already_built: 'It is already finished.',
    no_land: 'Pick a land first.',
    other: 'That could not be done.',
  } as Record<string, string>,
  names: NAMES_EN,
  finishNow: 'FINISH NOW',
  finishNote: 'Answer one question about this building and it is finished at once. A wrong answer costs nothing: the frame keeps building.',
  nextIn: (t: string) => `NEXT QUESTION IN ${t}`,
  right: (name: string) => `Right! ${name} is finished.`,
  wrong: 'Not quite. The frame keeps building, and another question comes in 30 seconds.',
  maths: 'THE MATHS OF IT',
  grade: 'GRADE',
  canvas: 'Your town. Use the arrow keys to move between tiles.',
  landmarkRises: (name: string, skill: string) => `${name} rises! Your first star in ${skill} raised it.`,
  landmarkBy: (skill: string) => `Raised by your first star in: ${skill}.`,
  sampleBy: (skill: string) => `Raised by a first star in: ${skill}.`,
  landmarkStars: (n: number) => `${n} of 3 stars in this mission.`,
  landmarkFixed: 'A landmark stays on its gold star: it is not bought, moved or removed.',
  landmarkNews: (name: string, skill: string) => `NEW LANDMARK: ${name.toUpperCase()}, FOR ${skill.toUpperCase()}`,
  landmarkWaits: (n: number) => `It stands on land ${n} once you open it.`,
  xr: {
    hint: 'Hold the grip or pinch on a shelf piece, let go on the land.',
    done: 'EXIT',
    zoomIn: 'ZOOM IN',
    zoomOut: 'ZOOM OUT',
    pan: 'MOVE',
    reset: 'RESET',
    resetDone: 'The land and the shelf are back as they were.',
    zoomed: (z: number) => `ZOOM ${z}x`,
    panOn: 'Hand tool: hold on the land and drag it to look around.',
    panOff: 'Hand tool off: pieces on the land can be taken again.',
    carry: (name: string) => `${name}: let go over a tile.`,
    dropRemove: (n: number) => `Let go here to remove it (+${n} Folds back).`,
    dropBack: 'Let go here to put it back on the shelf.',
    mapLater: 'Pick your place on the class map on the computer.',
    pickLandXr: 'PICK YOUR LAND: point at one and pinch',
    shelfHint: 'Pinch a piece and carry it onto the page.',
    page: (n: number, of: number) => `${n} / ${of}`,
    lockedShort: (n: number) => `AFTER ${n}`,
  },
};

const ID: typeof EN = {
  title: 'KOTA LIPATKU',
  folds: (n: number) => `${n} FOLDS`,
  close: 'TUTUP',
  land: (n: number) => `LAHAN ${n}`,
  newLand: 'LAHAN BARU',
  how: 'CARA MENDAPAT FOLDS',
  sampleOpen: 'LIHAT CONTOH KOTA',
  sampleTitle: 'CONTOH KOTA LIPAT',
  buildMine: 'BANGUN KOTAKU',
  sampleNote:
    'Contoh kota untuk dilihat saja: seperti apa kota bisa tumbuh setelah berminggu-minggu bermain, dengan landmark di setiap lahan. Pilih bangunan untuk melihat matematikanya, atau landmark untuk melihat skill yang membangunnya.',
  sampleKeys: 'Panah bergerak · Enter memilih · Esc menutup',
  loading: 'Membuka kotamu...',
  failed: 'Kota belum bisa dibuka di sini. Coba lagi.',
  shop: 'TOKO',
  price: (n: number) => `${n} Folds`,
  lockedAfter: (n: number) => `Setelah ${n} bangunan`,
  needFolds: (n: number) => `Kurang ${n} Folds`,
  keys: 'Panah memindah · R memutar · Enter menaruh · Delete menghapus · Esc berhenti',
  pickLand: 'PILIH LAHANMU',
  pickLandNote: 'Setiap lahan adalah satu halaman bukumu. Sungai, bukit, atau pantainya tetap ada, dan bintang emas menyimpan tempat untuk landmark yang kamu dapat dengan belajar.',
  kinds: {
    plain: ['DATARAN', 'Padang rumput, semua petak bisa dibangun.'],
    river: ['SUNGAI', 'Sungai melintas di tengah. Landmark pecahanmu bisa menjadi jembatannya.'],
    hills: ['BUKIT', 'Bukit hijau di satu sudut.'],
    beach: ['PANTAI', 'Pantai berpasir di sisi depan.'],
  },
  pickCell: 'PILIH TEMPATMU DI PETA KELAS',
  pickCellNote: 'Lahanmu bergabung dengan peta kelas di sini. Teman sekelas melihat nama pemainmu, gurumu melihat nomor kursimu. Pilih kotak yang kosong.',
  pickCellLater: 'Kamu sedang offline. Bangun sekarang; pilih tempatmu di peta kelas saat online lagi.',
  cellTaken: 'Kotak itu baru saja diambil teman. Pilih yang lain.',
  you: 'KAMU',
  later: 'NANTI',
  back: 'KEMBALI',
  status: {
    building: (t: string) => `Sedang dibangun: jadi dalam ${t}`,
    ready: 'Sudah jadi',
  },
  move: 'PINDAH',
  remove: 'HAPUS',
  refund: (n: number) => `HAPUS (+${n} FOLDS KEMBALI)`,
  turn: 'PUTAR',
  cancel: 'BATAL',
  placed: (name: string) => `${name} ditaruh.`,
  removed: (name: string, n: number) => `${name} dihapus, ${n} Folds kembali.`,
  moved: (name: string) => `${name} dipindah.`,
  finished: (name: string) => `${name} sudah jadi!`,
  tile: (x: number, y: number) => `Petak ${x + 1}, ${y + 1}`,
  empty: 'kosong',
  landClosed: (used: number, need: number) => `Bangun di ${need} petak lahan ini untuk membuka lahan baru (baru ${used}).`,
  refusedTitle: 'TIDAK DISIMPAN',
  refusedNote: 'Perubahan ini tidak bisa disimpan server, jadi kotamu mengikuti yang ada di server:',
  ok: 'OKE',
  offline: 'Offline: perubahanmu menunggu di perangkat ini dan terkirim saat online lagi.',
  howBody: [
    'Setiap permainan memberi Folds: satu untuk setiap 10 poin, dan 10 lagi karena selesai.',
    'Bermain beberapa hari berturut-turut menambah bonus beruntun, paling banyak 25 Folds sehari.',
    'Latihan dan lomba robot memberi paling banyak 100 Folds sehari; lomba kelas, ruang, dan CARI LAWAN tanpa batas.',
    'Bangunan baru berdiri sebagai kerangka kertas beberapa menit sebelum jadi. Menghapus bangunan mengembalikan semua Folds-nya.',
    'CITY BUILDER di papan peringkat menghitung Folds pada bangunanmu yang sudah jadi.',
  ],
  earned: (e) =>
    `Didapat: ${e.plays} dari permainan, ${e.streak} dari hari beruntun, ${e.welcome} hadiah sambutan${e.held_back ? `. ${e.held_back} tertahan batas harian.` : '.'}`,
  reasons: {
    not_enough_folds: 'Folds belum cukup. Main satu game untuk mendapat lagi.',
    look_only: 'Contoh kota hanya untuk dilihat. Bangun kotamu sendiri dengan BANGUN KOTAKU.',
    taken: 'Sudah ada bangunan di situ.',
    nature: 'Tidak bisa membangun di air, bukit, atau pasir.',
    landmark_plot: 'Bintang emas menyimpan dua petak ini untuk landmark.',
    needs_water: 'Jembatan dipasang di atas air.',
    off_land: 'Tidak muat di halaman di situ.',
    locked: 'Toko membukanya setelah lebih banyak bangunan.',
    land_not_full: 'Bangun lebih banyak di lahan ini dulu.',
    too_many_lands: 'Bukumu tidak punya halaman lagi.',
    unknown_place: 'Bangunan itu sudah tidak ada.',
    already_built: 'Bangunan itu sudah jadi.',
    no_land: 'Pilih lahan dulu.',
    other: 'Itu tidak bisa dilakukan.',
  },
  names: NAMES_ID,
  finishNow: 'SELESAIKAN SEKARANG',
  finishNote: 'Jawab satu soal tentang bangunan ini dan bangunan langsung jadi. Salah tidak apa-apa: kerangkanya tetap dibangun.',
  nextIn: (t: string) => `SOAL BERIKUTNYA ${t}`,
  right: (name: string) => `Benar! ${name} sudah jadi.`,
  wrong: 'Belum tepat. Kerangkanya tetap dibangun, dan soal baru datang 30 detik lagi.',
  maths: 'MATEMATIKANYA',
  grade: 'KELAS',
  canvas: 'Kotamu. Pakai tombol panah untuk berpindah antarpetak.',
  landmarkRises: (name: string, skill: string) => `${name} berdiri! Bintang pertamamu di ${skill} yang membangunnya.`,
  landmarkBy: (skill: string) => `Dibangun oleh bintang pertamamu di: ${skill}.`,
  sampleBy: (skill: string) => `Dibangun oleh bintang pertama di: ${skill}.`,
  landmarkStars: (n: number) => `${n} dari 3 bintang di misi ini.`,
  landmarkFixed: 'Landmark tetap di bintang emasnya: tidak dibeli, dipindah, atau dihapus.',
  landmarkNews: (name: string, skill: string) => `LANDMARK BARU: ${name.toUpperCase()}, DARI ${skill.toUpperCase()}`,
  landmarkWaits: (n: number) => `Berdiri di lahan ${n} setelah kamu membukanya.`,
  xr: {
    hint: 'Tahan grip atau cubit potongan di rak, lepas di atas lahan.',
    done: 'KELUAR',
    zoomIn: 'PERBESAR',
    zoomOut: 'PERKECIL',
    pan: 'GESER',
    reset: 'ULANG',
    resetDone: 'Lahan dan rak kembali seperti semula.',
    zoomed: (z: number) => `ZOOM ${z}x`,
    panOn: 'Alat tangan: tahan di atas lahan lalu seret untuk melihat ke sekeliling.',
    panOff: 'Alat tangan mati: potongan di lahan bisa diambil lagi.',
    carry: (name: string) => `${name}: lepaskan di atas petak.`,
    dropRemove: (n: number) => `Lepaskan di sini untuk menghapusnya (+${n} Folds kembali).`,
    dropBack: 'Lepaskan di sini untuk mengembalikannya ke rak.',
    mapLater: 'Pilih tempatmu di peta kelas lewat komputer.',
    pickLandXr: 'PILIH LAHANMU: tunjuk satu lalu cubit',
    shelfHint: 'Cubit satu potongan lalu bawa ke halaman.',
    page: (n: number, of: number) => `${n} / ${of}`,
    lockedShort: (n: number) => `SETELAH ${n}`,
  },
};

export const TOWN_TEXT: Record<Lang, typeof EN> = { en: EN, id: ID };
export type TownText = typeof EN;

/** A wait as minutes and seconds, or hours and minutes. */
export function waitText(ms: number, lang: Lang): string {
  const s = Math.max(0, Math.ceil(ms / 1000));
  if (s >= 3600) {
    const h = Math.floor(s / 3600);
    const m = Math.floor((s % 3600) / 60);
    return lang === 'id' ? `${h} jam ${m} menit` : `${h} h ${m} min`;
  }
  return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`;
}
