// Written by scripts/town-pack.ts from scripts/town-shop.ts; edit those instead.

/** Every piece of the town by name, in English. */
export const NAMES_EN: Record<string, string> = {
  road_straight: 'Road',
  road_corner: 'Road corner',
  road_t: 'T junction',
  road_cross: 'Crossroads',
  road_end: 'Dead end',
  path_straight: 'Footpath',
  path_corner: 'Footpath corner',
  path_t: 'Footpath T',
  path_cross: 'Footpath cross',
  road_dirt_straight: 'Dirt road',
  road_dirt_corner: 'Dirt road corner',
  road_crosswalk: 'Zebra crossing',
  bridge_road: 'Bridge',
  parking_lot: 'Car park',
  road_roundabout: 'Roundabout',
  avenue_straight: 'Avenue',
  avenue_corner: 'Avenue corner',
  avenue_t: 'Avenue T',
  avenue_cross: 'Avenue cross',
  rail_straight: 'Railway',
  rail_corner: 'Railway corner',
  rail_crossing: 'Level crossing',
  highway_straight: 'Flyover',
  highway_corner: 'Flyover corner',
  highway_ramp: 'Flyover ramp',
  highway_over_road: 'Flyover over a road',
  tree_round: 'Round tree',
  tree_pine: 'Pine tree',
  plant_bush: 'Bush',
  plant_flower_bush: 'Flowering bush',
  tree_palm: 'Palm tree',
  tree_coconut: 'Coconut tree',
  plant_hedge: 'Hedge',
  plant_flower_pot: 'Flower pot',
  plant_flower_bed: 'Flower bed',
  tree_cypress: 'Cypress',
  tree_acacia: 'Acacia',
  plant_cactus: 'Cactus',
  plant_bamboo: 'Bamboo',
  tree_sakura: 'Cherry tree',
  tree_banyan: 'Banyan tree',
  nature_grass: 'Grass',
  nature_forest: 'Little forest',
  nature_rice_field: 'Rice field',
  nature_hill: 'Hill',
  nature_river_straight: 'Stream',
  nature_river_corner: 'Stream bend',
  nature_beach: 'Beach',
  prop_bench: 'Bench',
  prop_street_lamp: 'Street lamp',
  prop_trash_bins: 'Bins',
  prop_fence: 'Fence',
  prop_mailbox: 'Postbox',
  prop_fountain: 'Fountain',
  prop_bus_stop: 'Bus stop',
  prop_traffic_light: 'Traffic light',
  prop_stop_sign: 'Stop sign',
  prop_warning_sign: 'Warning sign',
  prop_direction_sign: 'Signpost',
  prop_hydrant: 'Fire hydrant',
  prop_cafe_table: 'Cafe table',
  prop_beach_umbrella: 'Beach umbrella',
  prop_phone_booth: 'Phone box',
  prop_vending_machine: 'Vending machine',
  prop_flagpole: 'Flagpole',
  prop_statue: 'Statue',
  billboard_standing: 'Sandwich board',
  billboard_pole: 'Billboard',
  billboard_wide: 'Wide billboard',
  billboard_rooftop: 'Rooftop sign',
  billboard_digital: 'Digital screen',
  people_man: 'Man',
  people_woman: 'Woman',
  people_child: 'Child with a balloon',
  people_student: 'Student',
  people_hijab: 'Woman in a hijab',
  people_elderly: 'Grandparent',
  people_jogger: 'Jogger',
  people_sitting: 'Sitting person',
  people_umbrella: 'Person with an umbrella',
  people_office_worker: 'Office worker',
  people_cyclist: 'Cyclist',
  people_vendor: 'Street vendor',
  people_police: 'Police officer',
  people_doctor: 'Doctor',
  people_worker: 'Builder',
  vehicle_bicycle: 'Bicycle',
  vehicle_sedan: 'Car',
  vehicle_hatchback: 'Small car',
  vehicle_motorcycle: 'Motorbike',
  vehicle_becak: 'Becak',
  vehicle_bajaj: 'Bajaj',
  vehicle_taxi: 'Taxi',
  vehicle_suv: 'SUV',
  vehicle_pickup: 'Pickup truck',
  vehicle_van: 'Van',
  vehicle_bus: 'Bus',
  vehicle_school_bus: 'School bus',
  vehicle_police: 'Police car',
  vehicle_ambulance: 'Ambulance',
  vehicle_fire_truck: 'Fire engine',
  vehicle_truck: 'Lorry',
  vehicle_train_locomotive: 'Train engine',
  vehicle_train_carriage: 'Train carriage',
  animal_cat: 'Cat',
  animal_bird: 'Bird',
  animal_cow: 'Cow',
  animal_monkey: 'Monkey',
  animal_penguin: 'Penguin',
  animal_zebra: 'Zebra',
  animal_giraffe: 'Giraffe',
  animal_lioness: 'Lioness',
  animal_lion: 'Lion',
  animal_elephant: 'Elephant',
  house_hut: 'Hut',
  house_cottage: 'Cottage',
  house_basic: 'House',
  house_stilt: 'Stilt house',
  house_minimalist: 'Flat roof house',
  house_row: 'Terraced houses',
  house_garage: 'House with a garage',
  house_two_storey: 'Two storey house',
  house_bungalow: 'Bungalow',
  house_garden: 'House with a garden',
  house_joglo: 'Joglo house',
  house_gadang: 'Gadang house',
  house_colonial: 'Colonial house',
  house_modern_glass: 'Glass house',
  house_duplex: 'Semi-detached houses',
  house_apartment: 'Small block of flats',
  house_villa_pool: 'Villa with a pool',
  house_flats: 'Tower of flats',
  house_luxury: 'Modern mansion',
  house_mansion: 'Palace',
  park_flower: 'Flower garden',
  park_picnic: 'Picnic park',
  park_playground: 'Playground',
  park_pond: 'Pond',
  park_fountain: 'Fountain park',
  park_community_garden: 'Community garden',
  park_zen: 'Rock garden',
  park_statue: 'Statue park',
  park_square: 'Town square',
  sport_basketball: 'Basketball court',
  sport_badminton: 'Badminton court',
  sport_tennis: 'Tennis court',
  sport_skatepark: 'Skatepark',
  sport_pool: 'Swimming pool',
  sport_soccer: 'Football pitch',
  sport_stadium: 'Stadium',
  zoo_gate: 'Zoo gate',
  zoo_penguin: 'Penguin pool',
  zoo_monkey: 'Monkey island',
  zoo_aviary: 'Aviary',
  zoo_giraffe: 'Giraffe pen',
  zoo_lion: 'Lion den',
  zoo_elephant: 'Elephant pen',
  shop_general: 'Corner shop',
  office_shophouse: 'Shophouse',
  shop_cafe: 'Cafe',
  shop_minimarket: 'Minimarket',
  shop_restaurant: 'Restaurant',
  shop_gas_station: 'Petrol station',
  shop_bank: 'Bank',
  shop_cinema: 'Cinema',
  shop_market: 'Market',
  shop_hotel: 'Hotel',
  shop_mall: 'Shopping mall',
  office_small: 'Small office',
  office_creative: 'Creative studio',
  office_campus: 'Business park',
  office_glass_tower: 'Office tower',
  office_stepped: 'Stepped tower',
  office_round: 'Round tower',
  office_helipad: 'Tower with a helipad',
  office_twin: 'Twin towers',
  office_spire: 'Skyscraper',
  industry_silo: 'Silo',
  industry_warehouse: 'Warehouse',
  industry_factory: 'Factory',
  public_kindergarten: 'Kindergarten',
  public_school: 'School',
  public_clinic: 'Health centre',
  public_post_office: 'Post office',
  public_library: 'Library',
  public_mosque: 'Mosque',
  public_church: 'Church',
  public_temple: 'Temple',
  public_police: 'Police station',
  public_fire_station: 'Fire station',
  public_water_tower: 'Water tower',
  public_bus_terminal: 'Bus station',
  public_museum: 'Museum',
  public_train_station: 'Train station',
  public_hospital: 'Hospital',
  public_city_hall: 'Town hall',
  public_university: 'University',
  public_power_plant: 'Power station',
  public_airport: 'Airport',
  landmark_fraction_bridge: 'Fraction Bridge',
  landmark_times_tower: 'Times Tower',
  landmark_number_hall: 'Number Hall',
  landmark_decimal_market: 'Decimal Market',
  landmark_clock_tower: 'Clock Tower',
};

/** Every piece of the town by name, in Indonesian. */
export const NAMES_ID: Record<string, string> = {
  road_straight: 'Jalan',
  road_corner: 'Tikungan',
  road_t: 'Pertigaan',
  road_cross: 'Perempatan',
  road_end: 'Jalan buntu',
  path_straight: 'Jalan setapak',
  path_corner: 'Tikungan setapak',
  path_t: 'Pertigaan setapak',
  path_cross: 'Perempatan setapak',
  road_dirt_straight: 'Jalan tanah',
  road_dirt_corner: 'Tikungan jalan tanah',
  road_crosswalk: 'Zebra cross',
  bridge_road: 'Jembatan',
  parking_lot: 'Parkiran',
  road_roundabout: 'Bundaran',
  avenue_straight: 'Jalan raya',
  avenue_corner: 'Tikungan jalan raya',
  avenue_t: 'Pertigaan jalan raya',
  avenue_cross: 'Perempatan jalan raya',
  rail_straight: 'Rel kereta',
  rail_corner: 'Tikungan rel',
  rail_crossing: 'Perlintasan kereta',
  highway_straight: 'Jalan layang',
  highway_corner: 'Tikungan jalan layang',
  highway_ramp: 'Tanjakan jalan layang',
  highway_over_road: 'Jalan layang di atas jalan',
  tree_round: 'Pohon bulat',
  tree_pine: 'Pohon pinus',
  plant_bush: 'Semak',
  plant_flower_bush: 'Semak berbunga',
  tree_palm: 'Pohon palem',
  tree_coconut: 'Pohon kelapa',
  plant_hedge: 'Pagar tanaman',
  plant_flower_pot: 'Pot bunga',
  plant_flower_bed: 'Bedeng bunga',
  tree_cypress: 'Pohon cemara',
  tree_acacia: 'Pohon akasia',
  plant_cactus: 'Kaktus',
  plant_bamboo: 'Bambu',
  tree_sakura: 'Pohon sakura',
  tree_banyan: 'Pohon beringin',
  nature_grass: 'Rumput',
  nature_forest: 'Hutan kecil',
  nature_rice_field: 'Sawah',
  nature_hill: 'Bukit',
  nature_river_straight: 'Sungai',
  nature_river_corner: 'Kelokan sungai',
  nature_beach: 'Pantai',
  prop_bench: 'Bangku',
  prop_street_lamp: 'Lampu jalan',
  prop_trash_bins: 'Tempat sampah',
  prop_fence: 'Pagar',
  prop_mailbox: 'Kotak pos',
  prop_fountain: 'Air mancur',
  prop_bus_stop: 'Halte',
  prop_traffic_light: 'Lampu lalu lintas',
  prop_stop_sign: 'Rambu stop',
  prop_warning_sign: 'Rambu peringatan',
  prop_direction_sign: 'Papan penunjuk arah',
  prop_hydrant: 'Hidran',
  prop_cafe_table: 'Meja kafe',
  prop_beach_umbrella: 'Payung pantai',
  prop_phone_booth: 'Telepon umum',
  prop_vending_machine: 'Mesin minuman',
  prop_flagpole: 'Tiang bendera',
  prop_statue: 'Patung',
  billboard_standing: 'Papan berdiri',
  billboard_pole: 'Papan reklame',
  billboard_wide: 'Baliho lebar',
  billboard_rooftop: 'Papan atap',
  billboard_digital: 'Papan digital',
  people_man: 'Pria',
  people_woman: 'Wanita',
  people_child: 'Anak dengan balon',
  people_student: 'Pelajar',
  people_hijab: 'Wanita berhijab',
  people_elderly: 'Lansia',
  people_jogger: 'Pelari',
  people_sitting: 'Orang duduk',
  people_umbrella: 'Orang berpayung',
  people_office_worker: 'Pekerja kantor',
  people_cyclist: 'Pesepeda',
  people_vendor: 'Pedagang gerobak',
  people_police: 'Polisi',
  people_doctor: 'Dokter',
  people_worker: 'Pekerja proyek',
  vehicle_bicycle: 'Sepeda',
  vehicle_sedan: 'Mobil sedan',
  vehicle_hatchback: 'Mobil kecil',
  vehicle_motorcycle: 'Motor',
  vehicle_becak: 'Becak',
  vehicle_bajaj: 'Bajaj',
  vehicle_taxi: 'Taksi',
  vehicle_suv: 'Mobil SUV',
  vehicle_pickup: 'Mobil pikap',
  vehicle_van: 'Mobil van',
  vehicle_bus: 'Bus kota',
  vehicle_school_bus: 'Bus sekolah',
  vehicle_police: 'Mobil polisi',
  vehicle_ambulance: 'Ambulans',
  vehicle_fire_truck: 'Mobil pemadam',
  vehicle_truck: 'Truk',
  vehicle_train_locomotive: 'Lokomotif',
  vehicle_train_carriage: 'Gerbong kereta',
  animal_cat: 'Kucing',
  animal_bird: 'Burung',
  animal_cow: 'Sapi',
  animal_monkey: 'Monyet',
  animal_penguin: 'Penguin',
  animal_zebra: 'Zebra',
  animal_giraffe: 'Jerapah',
  animal_lioness: 'Singa betina',
  animal_lion: 'Singa',
  animal_elephant: 'Gajah',
  house_hut: 'Gubuk',
  house_cottage: 'Rumah mungil',
  house_basic: 'Rumah',
  house_stilt: 'Rumah panggung',
  house_minimalist: 'Rumah minimalis',
  house_row: 'Rumah deret',
  house_garage: 'Rumah bergarasi',
  house_two_storey: 'Rumah dua lantai',
  house_bungalow: 'Bungalow',
  house_garden: 'Rumah berkebun',
  house_joglo: 'Rumah joglo',
  house_gadang: 'Rumah gadang',
  house_colonial: 'Rumah kolonial',
  house_modern_glass: 'Rumah kaca modern',
  house_duplex: 'Rumah kopel',
  house_apartment: 'Apartemen kecil',
  house_villa_pool: 'Villa berkolam',
  house_flats: 'Rumah susun',
  house_luxury: 'Rumah mewah',
  house_mansion: 'Istana',
  park_flower: 'Taman bunga',
  park_picnic: 'Taman piknik',
  park_playground: 'Taman bermain',
  park_pond: 'Taman kolam',
  park_fountain: 'Taman air mancur',
  park_community_garden: 'Kebun warga',
  park_zen: 'Taman batu',
  park_statue: 'Taman patung',
  park_square: 'Alun-alun',
  sport_basketball: 'Lapangan basket',
  sport_badminton: 'Lapangan bulu tangkis',
  sport_tennis: 'Lapangan tenis',
  sport_skatepark: 'Skatepark',
  sport_pool: 'Kolam renang',
  sport_soccer: 'Lapangan sepak bola',
  sport_stadium: 'Stadion',
  zoo_gate: 'Gerbang kebun binatang',
  zoo_penguin: 'Kolam penguin',
  zoo_monkey: 'Pulau monyet',
  zoo_aviary: 'Kandang burung',
  zoo_giraffe: 'Kandang jerapah',
  zoo_lion: 'Kandang singa',
  zoo_elephant: 'Kandang gajah',
  shop_general: 'Toko',
  office_shophouse: 'Ruko',
  shop_cafe: 'Kafe',
  shop_minimarket: 'Minimarket',
  shop_restaurant: 'Restoran',
  shop_gas_station: 'SPBU',
  shop_bank: 'Bank',
  shop_cinema: 'Bioskop',
  shop_market: 'Pasar',
  shop_hotel: 'Hotel',
  shop_mall: 'Mal',
  office_small: 'Kantor kecil',
  office_creative: 'Kantor kreatif',
  office_campus: 'Kampus bisnis',
  office_glass_tower: 'Menara kantor',
  office_stepped: 'Menara bertingkat',
  office_round: 'Menara silinder',
  office_helipad: 'Menara helipad',
  office_twin: 'Menara kembar',
  office_spire: 'Pencakar langit',
  industry_silo: 'Silo',
  industry_warehouse: 'Gudang',
  industry_factory: 'Pabrik',
  public_kindergarten: 'TK',
  public_school: 'Sekolah',
  public_clinic: 'Puskesmas',
  public_post_office: 'Kantor pos',
  public_library: 'Perpustakaan',
  public_mosque: 'Masjid',
  public_church: 'Gereja',
  public_temple: 'Pura',
  public_police: 'Kantor polisi',
  public_fire_station: 'Pemadam kebakaran',
  public_water_tower: 'Menara air',
  public_bus_terminal: 'Terminal bus',
  public_museum: 'Museum',
  public_train_station: 'Stasiun kereta',
  public_hospital: 'Rumah sakit',
  public_city_hall: 'Balai kota',
  public_university: 'Universitas',
  public_power_plant: 'Pembangkit listrik',
  public_airport: 'Bandara',
  landmark_fraction_bridge: 'Jembatan Pecahan',
  landmark_times_tower: 'Menara Perkalian',
  landmark_number_hall: 'Balai Angka',
  landmark_decimal_market: 'Pasar Desimal',
  landmark_clock_tower: 'Menara Jam',
};

/** The shop's shelves in order, with their names. */
export const SHELF_NAMES: [shelf: string, en: string, id: string][] = [
  ['roads', 'ROADS', 'JALAN'],
  ['homes', 'HOMES', 'RUMAH'],
  ['nature', 'NATURE', 'ALAM'],
  ['parks', 'PARKS', 'TAMAN'],
  ['shops', 'SHOPS & WORK', 'TOKO & KERJA'],
  ['public', 'PUBLIC', 'UMUM'],
  ['street', 'STREET', 'PERABOT'],
  ['life', 'PEOPLE & CARS', 'ORANG & MOBIL'],
];
