import type { Lang } from '../settings.js';
import type { Topic } from './questions.js';

/** The words of the smartboard race, in English and Indonesian. */
export const BOARD_TEXT = {
  en: {
    title: 'RACE ON THE SMARTBOARD',
    intro: 'Three players race through nine questions of the same kind, each with numbers of their own. Each one touches only their own column, where the answers come as animals, balloons and glowing orbs, taking turns.',
    grade: 'GRADE',
    topic: 'TOPIC',
    topics: { mixed: 'Mixed', PV: 'Place value', MD: 'Multiply and divide', FR: 'Fractions', DC: 'Decimals', ME: 'Measurement' } as Record<Topic, string>,
    players: 'PLAYERS',
    player: (n: number) => `Player ${n}`,
    fromClass: 'Students from',
    noClass: 'No class: type the names',
    loading: 'Loading...',
    pick: 'Pick a student',
    record: 'Save the results in the class report',
    distinct: 'Pick three different students.',
    start: 'START',
    close: 'CLOSE',
    go: 'GO!',
    finished: 'FINISHED',
    waiting: 'Waiting for the others...',
    pass: 'PASS',
    end: 'END RACE',
    endSure: 'END NOW?',
    results: 'RESULTS',
    right: (r: number, n: number) => `${r} of ${n} right`,
    unfinished: (a: number, n: number) => `answered ${a} of ${n}`,
    again: 'RACE AGAIN',
    setup: 'NEW SETUP',
    saving: 'Saving the results...',
    saved: 'Saved in the class report.',
    failed: 'The results could not be saved. Check the network and try again.',
    signIn: 'To save the results, sign in as the teacher on the home page first.',
    retry: 'TRY AGAIN',
    none: 'There are no questions for this grade and topic yet.',
  },
  id: {
    title: 'BALAPAN DI SMARTBOARD',
    intro: 'Tiga pemain berlomba menjawab sembilan soal sejenis, masing-masing dengan angkanya sendiri. Tiap pemain hanya menyentuh kolomnya sendiri. Jawabannya muncul bergantian sebagai binatang, balon dan orb bercahaya.',
    grade: 'KELAS',
    topic: 'TOPIK',
    topics: { mixed: 'Campuran', PV: 'Nilai tempat', MD: 'Kali dan bagi', FR: 'Pecahan', DC: 'Desimal', ME: 'Pengukuran' } as Record<Topic, string>,
    players: 'PEMAIN',
    player: (n: number) => `Pemain ${n}`,
    fromClass: 'Siswa dari',
    noClass: 'Tanpa kelas: ketik namanya',
    loading: 'Memuat...',
    pick: 'Pilih siswa',
    record: 'Simpan hasilnya di laporan kelas',
    distinct: 'Pilih tiga siswa yang berbeda.',
    start: 'MULAI',
    close: 'TUTUP',
    go: 'MULAI!',
    finished: 'SELESAI',
    waiting: 'Menunggu yang lain...',
    pass: 'LEWATI',
    end: 'AKHIRI BALAPAN',
    endSure: 'AKHIRI SEKARANG?',
    results: 'HASIL',
    right: (r: number, n: number) => `${r} dari ${n} benar`,
    unfinished: (a: number, n: number) => `menjawab ${a} dari ${n}`,
    again: 'BALAPAN LAGI',
    setup: 'ATUR ULANG',
    saving: 'Menyimpan hasil...',
    saved: 'Tersimpan di laporan kelas.',
    failed: 'Hasilnya belum tersimpan. Periksa jaringan, lalu coba lagi.',
    signIn: 'Untuk menyimpan hasil, masuk dulu sebagai guru di halaman utama.',
    retry: 'COBA LAGI',
    none: 'Belum ada soal untuk kelas dan topik ini.',
  },
} satisfies Record<Lang, unknown>;

export type BoardText = (typeof BOARD_TEXT)['en'];
